Adapt Issue Replicator to process diki findings
open-component-model/delivery-service pull request #105
Opened 2024-07-11 15:42 UTC by AleksandarSavchev

**What this PR does / why we need it**:
This PR improves the Issue Replicator by allowing it to create multiple issues for an artefact per found findings for it by setting the `enable_issue_per_finding` field of `finding_type_issue_replication_configs` to `true`.

There are a few minor changes to the old flow of issues creation, the iteration of issues is done in a later state and now when there are 2 or more open issues with the specific label a warning is logged as suppose to an Error.

The new flow of creating issues per finding differs by iterating all findings and executing `_create_or_update_issue` per finding, it also deletes all know issues that had not been updates or created.

This PR also adapts Issues Replicator to be able to process findings of type `finding/diki`.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```noteworthy user
Added a new `enable_issue_per_finding` field to `finding_type_issue_replication_configs`, which when set to `true` creates issues per finding for artefact.
```
```improvement user
Issue Replicator can now process findings of type `finding/diki`.
```

2024-07-12 12:44 UTC, 8R0WNI3 requested changes

2024-07-12 12:44 UTC, 8R0WNI3 commented on issue_replicator/github.py
> +            logger.warning(f'more than one open issue found with labels {labels}')
In which case should more than one issue actually be acceptable? If I understand it correctly, this function is called per finding in `_create_or_update_or_close_issues_per_finding`, and there should only be one issue per finding shouldn't it?

2024-07-12 12:44 UTC, 8R0WNI3 commented on issue_replicator/github.py
> +    findings_list = list(findings_by_versions.items())
nit: use `findings_by_versions.values()` instead if you don't need the keys anyways

2024-07-15 08:27 UTC, AleksandarSavchev commented on config.py
> +    enable_issue_per_finding: bool
I have now added a new function `deserialise_finding_type_issue_replication_cfg()` where the defaulting will take place. I have also set `enable_issue_assignees` to default to `False`, I find it similar to `enable_issue_per_finding` and feel it should also be set to default. WDYT?

2024-07-15 08:28 UTC, AleksandarSavchev commented on issue_replicator/github.py
> +            logger.warning(f'more than one open issue found with labels {labels}')
In the case where the scan config changes.

For example if for a `finding_type_issue_replication_config` the `enable_issue_per_finding` field was set to `true` and issues were created per finding, then `enable_issue_per_finding` is set to `false`. It would try to create a single issue but would find that multiple have already been created with the specific `correlation_id` and `cfg-name`. With the old logic the replicator would have errored, while now it would simply log this disturbance.

Perhaps we could add logic to manage such case and for the scan config to be able to freely switch between single or multiple issues? Currently it does work correctly when switching form single to multiple issues but not the other way around. WDYT?

2024-07-15 08:43 UTC, 8R0WNI3 commented on issue_replicator/github.py
> +            logger.warning(f'more than one open issue found with labels {labels}')
I see, thank you for clarifying! :-) Regarding your points, I think it is valid to dismiss the `RuntimeError` here 👍🏼

2024-07-15 08:52 UTC, 8R0WNI3 approved these changes
Just a very minor nit, otherwise /lgtm

2024-07-15 08:52 UTC, 8R0WNI3 commented on config.py
> +            )
nit: de-dent parenthesis

2024-07-15 08:52 UTC, 8R0WNI3 commented on config.py
> +    enable_issue_per_finding: bool
Yes I agree, thank you for picking this up :-)

2024-07-17 09:24 UTC, AleksandarSavchev commented
Made a force push to resolve conflicts

2024-07-17 10:30 UTC, 8R0WNI3 submitted a review, later dismissed
/lgtm

2024-07-18 08:58 UTC, 8R0WNI3 approved these changes

2024-07-18 09:23 UTC, merged