Add cfg option to restrict finding types of BDBA scan
open-component-model/delivery-service pull request #156
Opened 2024-08-30 10:58 UTC by 8R0WNI3

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

2024-09-02 08:30 UTC, ccwienk requested changes
I have some concerns:

If we introduce this `include_finding_types` (naming-nit: I think the include-prefix might be dropped), too my understanding, this means: either use default (-> all), or an explicit (subset). This has the slight disadvantage of potentially missing future extensions.

Therefore, I think it would be beneficial to invert the logic, and add a "blacklist" of metrics to ignore. We do not even have to be strict here. If an unknown value is suppressed, we could ignore it (we might emit a warning from an explicit cfg-checker). Rationale behind such different design: considering OGaaS, I think we we should make our cfg less of a burden w.r.t future refactorings.

2024-09-02 08:35 UTC, 8R0WNI3 commented on config.py
> +        # BDBA only supports rescorings (i.e. triages) for vulnerabilites
Yes, OCM-Gear does offer license rescorings. However, this is about which metadata types are going to be imported from BDBA to the delivery-db. And since _BDBA_ does not offer license rescorings, there are no rescorings to import in that case.

2024-09-02 08:36 UTC, 8R0WNI3 commented on config.py
> +            filtered_list.append(value)
Yes, but it does warn about unexpected values in that case.

2024-09-03 15:09 UTC, ccwienk submitted a review, later dismissed

2024-09-03 16:54 UTC, merged