Create flexible artefact access resolver
open-component-model/delivery-service pull request #179
Opened 2024-09-17 12:08 UTC by zkdev

Useful to support various artefact types.
Can be used as a callback for code which should not bother with resolving ocm artefacts.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

2024-09-18 12:28 UTC, 8R0WNI3 requested changes

2024-09-18 12:28 UTC, 8R0WNI3 commented on ocm_util.py
> +    ):
nit: missing type hint for return type

2024-09-18 12:28 UTC, 8R0WNI3 commented on ocm_util.py
> +                raise ValueError('`oci_client` must not be empty')
Why did you choose not to provide a default oci client here (e.g. by using `ccc.oci` module)?

2024-09-18 12:28 UTC, 8R0WNI3 commented on ocm_util.py
> +            return _resolve_local_blob(
`_resolve_local_blob` also requires `oci_client` to be set

2024-09-19 11:08 UTC, ccwienk commented on ocm_util.py
> +def create_resolve_access(
can we keep that slightly less generic? I was thinking of something like this:
```
def iter_s3_content(s3_client + s3-specific args) -> Generator[bytes, None, None]:
   ....

def iter_local_blob_content(oci_client, .....) ....
    ...

# place in code where scan_job-method is called:
if access.type is "s3":  # (please use enum, of course, this is lazy pseudocode)
  content_iterator = iter_s3_content(pass-in required specific args, partially from access, partially from "ccc")
elif access.type is "local-oci-blob": # i think you get the idea
  content_iterator = iter_local_blob(...)
else:
  not sure: ignore or raise?
```

So you see, I suggest to keep it less frame-worky, and have less abstrations, specifically, because we are at the only place where we have this logic, and we do not intend (at least not now) to expose it to other usages.

2024-09-23 14:29 UTC, merged