Accept artefact access resolve callback in BDBA
open-component-model/delivery-service pull request #180
Opened 2024-09-17 12:27 UTC by zkdev

Useful preparation to support more artefact types, e.g. local blobs.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

2024-09-18 12:32 UTC, 8R0WNI3 approved these changes
/lgtm

However, we'll also have to adjust the calling code here to pass-in the appropriate resolver function.

2024-09-19 11:02 UTC, ccwienk requested changes

2024-09-19 11:02 UTC, ccwienk commented on bdba/scanning.py
> +        blob_resolve_callback: ResolveArtefactAccess,
why not directly pass-in the generator, rather than a resolver? that way, the caller has more control, and this method is more generic.

2024-09-20 14:19 UTC, zkdev commented on bdba/scanning.py
> +        blob_resolve_callback: ResolveArtefactAccess,
that is what I proposed in the very first draft of this PR ...
will adjust, has some dependencies on other PRs

2024-09-23 12:43 UTC, closed without merging