feat: Optionally get raw component-descriptor
open-component-model/delivery-service pull request #183
Opened 2024-09-18 14:52 UTC by zkdev

Useful for debugging.
Also add option to bypass cache for this request.
Raw component-descriptors are never cached (for now).

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

2024-09-19 11:01 UTC, ccwienk requested changes

2024-09-19 11:01 UTC, ccwienk commented on components.py
> +    ocm_repos = cnudie.retrieve.iter_ocm_repositories(
inline into for-loop?

2024-09-19 11:01 UTC, ccwienk commented on components.py
> +) -> bytes:
generally-speaking, we might consider to factor-out the raw-retrieval-part (might be a candidate for cnudie.retrieve). The lookup might re-use a factored-out retrieval-function, wdty?

2024-09-20 13:44 UTC, zkdev commented on components.py
> +) -> bytes:
done with https://github.com/gardener/cc-utils/commit/5f2405cca856359b1d9cb8c557de536845a50dbb

2024-09-20 13:50 UTC, merged