Extend greatest_component_versions to support filtering by date range
open-component-model/delivery-service pull request #197
Opened 2024-09-25 08:53 UTC by TuanAnh17N

**What this PR does / why we need it**:
This PR extends the greatest_component_versions route in the delivery-service to support filtering by a specified date range. Users can now provide optional start_date and end_date parameters to retrieve component versions within a specific timeframe. 
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
This PR is dependent on another PR. Please ensure both are reviewed together to maintain compatibility.
**Release note**:

```improvement operator

```

2024-09-25 09:18 UTC, zkdev requested changes

2024-09-25 09:18 UTC, zkdev commented on components.py
> +    start_date: datetime.datetime = None,
nit: pep8 recommends:
> Don’t use spaces around the = sign when used to indicate a keyword argument, or when used to indicate a default value for an unannotated function parameter

see https://peps.python.org/pep-0008/#other-recommendations

2024-09-25 09:18 UTC, zkdev commented on components.py
> +    start_date: datetime.datetime = None,
Our linting suite used to raise these 🤔

2024-09-25 09:18 UTC, zkdev commented on components.py
> +    lookup = cnudie.retrieve.create_default_component_descriptor_lookup(
rather use delivery-service specific `lookups.init_component_descriptor_lookup`, without delivery-service lookup of course

2024-09-25 09:18 UTC, zkdev commented on components.py
> +    if not start_date or not end_date:
how about also supporting the case if only start is defined?
end could default to "now"

2024-09-25 09:18 UTC, zkdev commented on components.py
> +        filtered_versions.append(version)
rather use generator to prevent mutation and enable early-exit semantics :-)

2024-09-27 06:07 UTC, 8R0WNI3 requested changes

2024-09-27 06:07 UTC, 8R0WNI3 commented on components.py
> +                if creation_date < end_date:
Not sure but mustn't this be
```
if creation_date > end_date:
   continue
   
if creation_date < start_date:
   break
```
Thinking about it, we might have a different understand of what the start and end date means. In my understanding, the `start_date` is the earlier one and the `end_date` the later one (i.e. today in the default case).

2024-09-27 06:07 UTC, 8R0WNI3 commented on components.py
> +        start_date = datetime.datetime.now().strftime('%Y-%m-%d')
`datetime.datetime` will always include the _date_ + _time_. Since you are dropping the _time_ part here anyways, why not directly using the _date_ part only, i.e. `datetime.date.today().isoformat()`?

2024-09-27 06:07 UTC, 8R0WNI3 commented on components.py
> +    start_date: datetime.datetime=None,
When calling this function, you pass-in a string argument for `start_date` and `end_date` (the unprocessed value of the URL param). Also in this function, you except values to be strings and convert other date objects into strings (i.e. using `strftime`). Hence, I would either change the type hint here to `str` or work on date objects only (and parse passed-in parameters to such).

2024-09-30 06:55 UTC, 8R0WNI3 reviewed
One remark, otherwise /lgtm

2024-09-30 06:55 UTC, 8R0WNI3 commented on components.py
> +    if not end_date:
This will have to be `start_date`, since `end_date` will be always `True` (-> we set a default value for `end_date` above :-))

2024-09-30 07:24 UTC, 8R0WNI3 approved these changes
/lgtm

2024-09-30 07:29 UTC, merged