Use async web server
open-component-model/delivery-service pull request #202
Opened 2024-10-01 08:21 UTC by 8R0WNI3

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

2024-10-01 15:13 UTC, zkdev requested changes

2024-10-02 05:02 UTC, 8R0WNI3 commented on components.py
> +                query async for query in deliverydb.util.ArtefactMetadataQueries.component_queries(
It's because `component_queries` now returns an async generator, which is not allowed within `sa.or_`. Instead, it is first resolved asynchronously now and the resolved list is then passed to `sa.or_`.

2024-10-07 10:56 UTC, ccwienk commented
@8R0WNI3 : could you cherrypick the first six commits to `master` (and thus reduce the size of this pullrequest)?

- [Add util function to parse JSON responses](https://github.com/open-component-model/delivery-service/pull/202/commits/20141fff63a91b0cea36ce3e577dd606fd85ddc5)
- [Add util functions to parse request parameters](https://github.com/open-component-model/delivery-service/pull/202/commits/8ce8e21a2e87fc72342ed3e71062e9d4ecd3e76b)
- [Remove stale typing package usages](https://github.com/open-component-model/delivery-service/pull/202/commits/cb226a1114d91b6defa9944283234996ae2e13bf)
- [Remove deprecated ctx_repo_url parameter](https://github.com/open-component-model/delivery-service/pull/202/commits/9e51e3d0930883b82679c0e0131898d83a24927c)
- [Fix indentation](https://github.com/open-component-model/delivery-service/pull/202/commits/41783dde77b1669744bff563256191076112edf8)
- [Rename ctx_repo -> ocm_repo](https://github.com/open-component-model/delivery-service/pull/202/commits/485f7c7315bba067acbd9d388701aa9722157135)

2024-10-15 13:54 UTC, 8R0WNI3 commented on middleware/route_feature_check.py
> +            missing_features := _feature_name_set(required_features)
We could of course try to process the request first and and catch a `405 method not allowed` error eventually + react to it. However, I don't consider this a desirable solution so I would prefer to just stick to this logic for now and rely on proper documentation 🙈

2024-10-15 14:26 UTC, 8R0WNI3 commented on middleware/errors.py
> +            raise error
Well, this comment is a copy-pasta leftover... Actually, I'm not even sure what it is supposed to mean, we show errors in delivery-service logs and the client only receives http errors anyways 🤔

2024-10-15 14:42 UTC, 8R0WNI3 commented on artefacts.py
> +        unzip = util.param_as_bool(params, 'unzip', default=True)
Unfortunately not 😞

2024-10-15 14:47 UTC, 8R0WNI3 commented on caching.py
> +                return cache.__get_item__(filepath)
No, no reason behind this just a bad choice -> will adjust

2024-10-16 05:31 UTC, 8R0WNI3 commented on components.py
> +        subquery = sa.select(
Basically, because `query` is still the legacy usage (which is also based on `select` internally) and not included in the async session object anymore. However, I also think `select` is more intuitive since it mirrors SQL quite well.

2024-10-16 05:33 UTC, 8R0WNI3 commented on components.py
> +        tags:
Yes, everything before the separator is not interpreted by the documentation generator and everything afterwards is used for it.

2024-10-16 09:29 UTC, ccwienk submitted a review, later dismissed
see inline nit

2024-10-16 09:29 UTC, ccwienk commented on caching.py
> +            cache.__setitem__(filepath, result)
nit: since we not overwrite __setitem__ | __getitem__, we might use `cache[filepath] = result`

2024-10-16 12:05 UTC, merged