This commit will upload CM06 scan results to the delivery database(locally) while avoiding duplicate rescans of component versions.
open-component-model/delivery-service pull request #213
Opened 2024-10-14 12:03 UTC by TuanAnh17N

**What this PR does / why we need it**:
This PR uploads the CM06 scan results to the delivery database and ensures that component versions are not rescanned if they have already been processed. 

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

2024-10-15 06:06 UTC, 8R0WNI3 requested changes

2024-10-15 06:06 UTC, 8R0WNI3 commented on cm06.py
> +    all_findings = []
nit: Considering these are not _all_ findings but rather _new_ findings, let us also express that in the variable naming :-)

2024-10-15 06:06 UTC, 8R0WNI3 commented on cm06.py
> +        findings = list(_iter_sast_linting_findings(component_nodes))
My understanding so far was that we consider those components to have a "finding", which do not have sast linting enabled yet (as those components do not fulfill the given requirements). Looking at the code, it seems it is the other way around (we store "findings" for those components which have already enabled sast linting). What is actually our target picture here?

/cc @zkdev

2024-10-16 10:37 UTC, zkdev commented on cm06.py
> +        findings = list(_iter_sast_linting_findings(component_nodes))
In the end, both options would work. `artefact-scan-info` entry is used to differentiate whether a scan was performed at all.

I think consistency is a valid concern, therefore I prefer you store "findings" (in that: components without SAST linting).

2024-10-16 12:07 UTC, ccwienk commented on cm06.py
> +        for label in resource.labels:
use find_label

2024-10-16 12:08 UTC, ccwienk commented on cm06.py
> +    cnode: cnudie.iter.ComponentNode
I think it would make more sense to have this function accept a Component, rather than a ComponentNode

2024-10-16 12:09 UTC, ccwienk commented on cm06.py
> +@dataclasses.dataclass(frozen=True)
I think we should rather not make this class frozen, esp. considering artefact is not frozen / immutable.

2024-10-16 12:10 UTC, ccwienk commented on cm06.py
> +    blob_data: bytes
rather keep a callback (generator) yielding the data, instead of keeping it by value (consider large amounts of elements, which might lead to a lot of memory consumption)

2024-10-16 12:11 UTC, ccwienk commented on cm06.py
> +def extract_labels(
add docstr explaining what this function does. also, extraction does not seem to be adequate to me, considering there is some transormation + deduplication in place

2024-10-16 12:12 UTC, ccwienk commented on cm06.py
> +def retrieve_blob_data(
rather have this function return a generator yielding chunks of bytes

2024-10-16 12:12 UTC, ccwienk requested changes
see inline comments

2024-10-18 06:36 UTC, 8R0WNI3 requested changes

2024-10-18 06:36 UTC, 8R0WNI3 commented on cm06.py
> +            if find_label.name == 'cloud.gardener.cnudie/dso/scanning-hints/source_analysis/v1':
Rather use [already existing constant](https://github.com/gardener/cc-utils/blob/ba73bdd708ea8a2329650a4c6c2d81b41903046d/dso/labels.py#L51) here.

2024-10-18 06:36 UTC, 8R0WNI3 commented on cm06.py
> +        for find_label in source.labels:
Instead of changing the variable name to `find_label`, @ccwienk actually meant to use [already existing function](https://github.com/gardener/cc-utils/blob/ba73bdd708ea8a2329650a4c6c2d81b41903046d/ocm/__init__.py#L224) `find_label` which is defined by each OCM artefact.

2024-10-18 06:36 UTC, 8R0WNI3 commented on cm06.py
> +                    return resource
I think this logic does not quite fit the purpose of this `find_non_sast_linting_resource` function. So, it does the following:
- iterate over all resources of the component
   - iterate over all labels of the resource
      - if there is a label which does not match the expected one, and this label (not matching the expected label) does also not contain desired values, the whole component is declared as "not having sast linting"

Example:
If the `github.com/gardener/cc-utils` component (which actually _has_ sast linting enabled) would contain at least one resource, which has at least one label `!= 'gardener.cloud/purposes'` (e.g. a responsibles label or anything other), this label would most probably also not contain `sast` and `lint` in the value field and thus the whole `cc-utils` component would be considered "not having sast linting".

2024-10-18 06:36 UTC, 8R0WNI3 commented on cm06.py
> +class ComponentSASTLintingInfo:
I think this dataclass is actually not required anymore, since objects of type `dso.model.ComponentArtefactId` also contain the `component_name` and `component_version` property and I guess there is no additional benefit of keeping them redundant.

2024-10-18 06:36 UTC, 8R0WNI3 commented on cm06.py
> +        if resource:
nit: you can use assignment operator (`:=`) directly in-line of condition to save a line:

```
if resource := find_non_sast_linting_resource(cnode.component):
```

2024-10-18 06:36 UTC, 8R0WNI3 commented on cm06.py
> +    parser.add_argument(
I think there is no additional benefit from explicitly configuring `ocm-repo-urls` here. We already use `lookups`' component descriptor lookup and we can also stop passing `ocm_repo` to retrieve greatest component versions (this will then use delivery-service's OCM repo mapping in the end).

2024-10-18 06:36 UTC, 8R0WNI3 commented on cm06.py
> +            artefact=dso.model.ComponentArtefactId(
We already store the `ComponentArtefactId` object in `evidence`, so we can just re-use it instead of creating a new object.

2024-10-18 07:00 UTC, TuanAnh17N commented on cm06.py
> +    parser.add_argument(
true

2024-10-18 07:13 UTC, TuanAnh17N commented on cm06.py
> +        for find_label in source.labels:
XD

2024-10-21 08:07 UTC, zkdev requested changes

2024-10-21 08:07 UTC, zkdev commented on cm06.py
> +        label = ocm.LabelMethodsMixin.find_label(source, name=dso.labels.SourceScanLabel.name)
Determining whether a component contains a SAST artefact and evaluating SAST policy labels are two different concerns. I suggest to rather evaluate SAST policies upfront and only process the relevant components.

2024-10-21 08:07 UTC, zkdev commented on cm06.py
> +        logger.info(f'Processing comp-version {component_version} [{i}/{len(landscape_versions)}]')
nit: either use full qualified term "component version", or drop entirely
rational: these are worker internal logs and it is to be expected that only domain experts will evaluate them -> they are familiar with OCM. Also, introducing custom abbreviations just adds noise and inconsistency which can ultimately make things harder to understand

2024-10-21 08:10 UTC, 8R0WNI3 requested changes

2024-10-21 08:10 UTC, 8R0WNI3 commented on cm06.py
> +                artefact=dso.model.component_artefact_id_from_ocm(
The object returned by `dso.model.component_artefact_id_from_ocm` is of type `dso.model.ComponentArtefactId` and _not_ of type `dso.model.LocalArtefactId`. Hence, you should directly yield from the function instead of building a new `dso.model.ComponentArtefactId` object.

2024-10-21 08:10 UTC, 8R0WNI3 commented on cm06.py
> +        type=dso.model.Datatype.EVIDENCE_SAST_LINTING,
I think we should rather name this type something like `FINDING_NO_SAST_LINTING` or similar ever since we decided to track those components which _don't_ have sast linting instead of the other way round.

2024-10-21 08:10 UTC, 8R0WNI3 commented on cm06.py
> +        logger.info(f'Processing comp-version {component_version} [{i}/{len(landscape_versions)}]')
We'll also have to upload a artefact metadata entry of type `dso.model.Datatype.ARTEFACT_SCAN_INFO` for each component version. With said type, we store information whether a certain component version was actually "scanned", so we can conclude from the absence of a "finding" + the information that the component version _was_ actually scanned, that it has sast linting enabled. You can use [this already existing function](https://github.com/gardener/cc-utils/blob/1f615b157555f7549fe376d79389f16bdde27a92/dso/model.py#L467) to create the respective object.

2024-10-21 14:37 UTC, 8R0WNI3 requested changes

2024-10-21 14:37 UTC, 8R0WNI3 commented on cm06.py
> +) -> ocm.Resource | None:
Please also adjust the type hint (`-> bool`) to recent refactoring :-)

2024-10-21 14:37 UTC, 8R0WNI3 commented on cm06.py
> +        if (label and AnalysisLabel.LINT.value in label.value and
You can make an early exit `return False` in case this condition is `True`.

Also, currently `True` is returned in case there is _any_ resource where this condition evaluates to `False` (i.e. any resource which doesn't contain the required label). However, `True` should only be returned in case this condition evalutes to `False` for _all_ resources. So, you can add the early exit as described above for the `True` case, drop the `else` case and return `True` at the very end of the function. That's the case when none of the resources contains the required sast lint information.

2024-10-21 14:37 UTC, 8R0WNI3 commented on cm06.py
> +
As discussed, you _could_ use existing artefact scan info objects to examine that a component version was already scanned and thus skip the re-scan (we won't find anything new if we do a re-scan because we assume our component descriptors are immutable). However, I leave it up to you to do this or not since it's only an optimisation.

2024-10-21 14:37 UTC, 8R0WNI3 commented on cm06.py
> +        type=[dso.model.Datatype.FINDING_NO_SAST_LINTING, dso.model.Datatype.ARTEFACT_SCAN_INFO]
You don't have to query for `FINDING_NO_SAST_LINTING` here since the artefact scan infos contain all the required information of existing scans.

2024-10-21 18:02 UTC, ccwienk requested changes

2024-10-21 18:02 UTC, ccwienk commented on cm06.py
> +def has_non_sast_linting_resource(
can we overhaul this a bit, structure-wise (+ improve naming)?
I would imagine something like (pseudo-code):

```
SastClassification (Type):
 central_[sast]scans: enabled | disabled | unknown / default (the latter value expresses no explicit cfg was found)
 local_[sast]scans: <(possibly empty) list of sast-scans>

def central_sast_cfg(component) -> "enabled | disabled | unknown" (might be an enum-value?):

def local_sast_scans(component) -> "Generator[SastScan, None, None]":

def classify(component) -> SastClassification
  return SastClassification(
    central_scans=central_sast_cfg(component),
    local_sast_scans(local_sast_scans(component),
 )
```

Of course, you might add some properties for convenience, like so:
```
SastClassification:
  ...
  @property
  def is_okay(self) -> bool
    return self.local_sast_scans or self.central_scans
```

Note that I omitted the actual code (mostly) - those snippets should illustrate the structure-wise organisation I would suggest.

2024-10-21 18:02 UTC, ccwienk commented on cm06.py
> +def _iter_non_sast_linting_findings(
nit: why make this function "private"?

2024-10-21 18:02 UTC, ccwienk commented on cm06.py
> +    delivery_client.update_metadata(data=non_sast_linting_metadata+scan_info)
nit: whitespace around `+` operator

2024-10-21 18:02 UTC, ccwienk commented on cm06.py
> +                creation_date=datetime.datetime.now(),
nit: re-use timestamp-object. also, if db-schema allows it, preferably use tz-aware ts.

2024-10-28 15:30 UTC, closed without merging