Generalize rescoring rule model
open-component-model/delivery-service pull request #237
Opened 2024-11-08 09:39 UTC by TuanAnh17N

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

2024-11-08 09:45 UTC, zkdev requested changes

2024-11-08 09:45 UTC, zkdev commented on rescore/model.py
> +        rule_set_type: str
we might add `absent_ok` flag

2024-11-08 09:45 UTC, zkdev commented on rescore/artefacts.py
> +    default_cve_rescoring_rule_set: rm.RuleSet,
default ruleset(s) are not (yet?) considered with new structure, I think 🤔

2024-11-08 09:45 UTC, zkdev commented on config.py
> +        cve_rescoring_rule_set = None
`find_rule_set_by_type` will return `None` anyways, we can omit else case here

2024-11-11 08:37 UTC, zkdev requested changes

2024-11-11 08:37 UTC, zkdev commented on rescore/model.py
> -    description: str
we should add description-str again, will be especially helpful since we plan to introduce additional rule-sets :-)

2024-11-11 08:37 UTC, zkdev commented on rescore/model.py
> +class CveRescoringRule:
can we freeze it?
would be helpful considering `RuleSet` class expects `tuple` of `CveRescoringRule`

2024-11-11 08:37 UTC, zkdev commented on rescore/model.py
> +    raw: list[dict],
let us drop this function and inline in caller instead

2024-11-11 09:03 UTC, TuanAnh17N commented on rescore/model.py
> +    raw: list[dict],
since rescoring_rule_sets_from_raw is currently called three times outside the model.py, wouldn't inlining it just add unnecessary duplication?

2024-11-11 12:44 UTC, ccwienk reviewed
could you elaborate on the highlevel organisation of rulesets you suggest?

before this change, there was a global `(cve-)rulesets`, which was a list of (cve-)rescoring-rules.

or. yaml-ishly speaking:
```
rulesets: # each entry implicitly being a set of cve-rescoring-rulesets
 - name: my-rescoring-rules
   rules: # list of rules
```

In that example, the topmost attribute (rulesets) might be described /w a typehint `list[CVE_RescoringRuleset, ...]` whereas each CVE_RescoringRuleset would have a list (stored in `rules`) of `CVE_RescoringRule`

--

After the ongoing generalisation, I think we should have something like:

```
rulesets:
- name: my-cve-ruleset
  type: cve-rescoring
  rules: # cve-rescoring-rules
- name: my-sast-ruleset
  type: sast-rescoring
  rules: # sast-rescoring-rules
```

Thus, it will make sense to have a (generic, ideally w/ type-params) base-class for rulesets, and rulesettype-specific rules, like so (pseudo-pseudo-code - I might have gotten type-parameters wrong syntactically):

```
class Rule:
  name: str # probably, each rule should have a name

class RuleSet[T: Rule]:
  rules: list[T]

class CveRescoringRule(Rule):
   pass #...

class SastRescoringRule(Rule):
  pass # ...

class CveRescoringRuleset(Ruleset[CveRescoringRule]):
  pass
```

2024-11-11 12:44 UTC, ccwienk commented on app.py
>          features.FeatureRescoring,
codestyle/nit: store rescoring-feature in local variable to avoid calling get_feature twice

2024-11-11 12:44 UTC, ccwienk commented on bdba/scanning.py
> +        cve_rescoring_ruleset: rescore.model.RuleSet=None,
as indicated by the parameter-name + the processing, I think it will make sense to _do_ have a CveRescoringSet (which is a specialised variant of RuleSet)

2024-11-11 12:44 UTC, ccwienk commented on rescore/model.py
> +RuleSets = tuple[RuleSet]
codestyle: I think this should rather be inlined, where needed

2024-11-11 12:44 UTC, ccwienk commented on rescore/model.py
> +class RuleSet:
That does not seem like a good match. The base-class was renamed to be a generic RuleSet, whereas its rules are declared to be of type `CveRescoringRule`

2024-11-12 13:29 UTC, 8R0WNI3 requested changes

2024-11-12 13:29 UTC, 8R0WNI3 commented on config.py
> +        for rule_set_raw in rescoring_rulesets_raw['rescoringRuleSets']
Please add a check whether `rescoring_rulesets_raw` is actually defined.

2024-11-12 13:29 UTC, 8R0WNI3 commented on config.py
> +            type=rule_set_raw['type'],
I think the type should not be explicitly set here, but rather consumed from the default value for `CveRescoringRuleSet`. Instead, it must be used for filtering to prevent parsing different types of rule sets here.

2024-11-12 13:29 UTC, 8R0WNI3 commented on config.py
> +        cve_rescoring_rule_set = rescore.model.find_rule_set_for_type(
I did not see this filter when I wrote my previous comment, but still I'd prefer to move the filtering to the initial tuple comprehension. Otherwise, the name `cve_rescoring_rule_sets` is misleading (because at that point in time we did not know whether they are actually of type CVE) and also `cve_rescoring_rules_from_dicts` will be called for rule sets of other types (and thus might fail).

2024-11-12 13:29 UTC, 8R0WNI3 commented on config.py
> +        cve_rescoring_ruleset=cve_rescoring_rule_set,
Please either stick with `cve_rescoring_ruleset` or change it consistently to `cve_rescoring_rule_set`.

2024-11-12 13:29 UTC, 8R0WNI3 commented on features/__init__.py
> +        rule_set_type: str,
Rather use existing `RuleSetType` enum.

2024-11-12 13:29 UTC, 8R0WNI3 commented on features/__init__.py
> +            rs: rm.RuleSet
Since `rescoring_rule_sets` is type-hinted as list of `rm.RuleSet`, this explicit type hint is obsolete isn't it?

2024-11-12 13:29 UTC, 8R0WNI3 commented on features/__init__.py
> +        for rule_set_raw in rescoring_raw['rescoringRuleSets']
> I think the type should not be explicitly set here, but rather consumed from the default value for CveRescoringRuleSet. Instead, it must be used for filtering to prevent parsing different types of rule sets here.

Same applies here.

2024-11-13 15:31 UTC, 8R0WNI3 commented on rescore/model.py
> +        if rule_set.type == rule_set_type:
nit: Use identity comparison `is` for comparing enum values.

2024-11-13 15:31 UTC, 8R0WNI3 commented on app.py
> +import rescore.model
\<linting>`recore.model` is imported but not used\</linting>

2024-11-13 15:31 UTC, 8R0WNI3 commented on config.py
> +            rescore.model.CveRescoringRuleSet( #noqa:E1123
Why is this `#noqa:E1123` disablement of the linter required and reasonable?

2024-11-13 15:31 UTC, 8R0WNI3 commented on config.py
> +                type=rule_set_raw['type'],
nit: Redundant setting of type property is not required, as the `CveRescoringRuleSet` dataclass already sets a reasonable default (which is already validated against in the condition of the comprehension.

2024-11-13 15:31 UTC, 8R0WNI3 commented on config.py
> +            if rule_set_raw['type'] == rescore.model.RuleSetType.CVE
ditto: identity comparison using `is` for enums

2024-11-13 15:31 UTC, 8R0WNI3 commented on config.py
> +        cve_rescoring_ruleset = rescore.model.find_rule_set_for_type(
What is the reason to call this filter here? All elements in `cve_rescoring_rulesets` should already be of type `cve`.

2024-11-13 15:31 UTC, 8R0WNI3 commented on config.py
> +        cve_rescoring_ruleset = rescore.model.CveRescoringRuleSet( #noqa:E1123
ditto: reasoning for `#noqa:E1123`?

2024-11-13 15:31 UTC, 8R0WNI3 commented on features/__init__.py
> +                and rs.type == rule_set_type
ditto: identity comparison using `is` for enums

2024-11-13 15:31 UTC, 8R0WNI3 commented on features/__init__.py
> +        rm.CveRescoringRuleSet( #noqa:E1123
Ditto here with regards to linter + explicit setting of `type` property + enum identity comparison.

2024-11-13 18:33 UTC, TuanAnh17N commented on config.py
> +            rescore.model.CveRescoringRuleSet( #noqa:E1123
the linter exceptions `(# noqa:E1123)` are necessary in this case because pylint struggles with the specific inheritance pattern involving generic dataclasses. see [issue](https://github.com/pylint-dev/pylint/issues/9488)

2024-11-13 19:17 UTC, ccwienk commented on config.py
> +            rescore.model.CveRescoringRuleSet( #noqa:E1123
in that case, it might be nice to add a reference to mentioned issue (did not check whether it fully matches) close to linter-exception

2024-11-13 19:20 UTC, ccwienk commented on rescore/model.py
> +    rules: list[T]
since we have `list` (a mutable type) as a member, we should not (falsely) declare containing dataclass as frozen.

2024-11-13 19:45 UTC, ccwienk requested changes

2024-11-13 19:45 UTC, ccwienk commented on test/test_rescoring.py
> +    assert isinstance(cve_rescoring_rule_sets, tuple)
it is quite strange to assert `tuple` will return a tuple.

also, why use a fixture here? either inline the dict (currently, there is only one usage), or define the dict as a module-variable, and use it

2024-11-13 19:45 UTC, ccwienk commented on test/test_rescoring.py
> +    assert len(cve_rescoring_rule_sets) == 1
what's the point of checking the length? the test-data is defined as part of the test-setup. with a slight indirection, this boils down to:

```
my_tuple = (1, )

assert len(my_tuple) == 1
```

-> will work, but it does not test the actual payload-code (the one we implemented ourselves). put in other words: there is little point in testing python's stdlibs (here) :-)

2024-11-13 19:45 UTC, ccwienk commented on test/test_rescoring.py
> +    assert isinstance(cve_rescoring_rule_sets[0], rescore.model.CveRescoringRuleSet)
that's fine. however, why not also check some more. I would imagine a good test to look like so:

```
valid_raw_ruleset = {... # insert testing-code from above }
ruleset = next(rescore.model.cve_rescoring_rules_from_dicts(valid_raw_ruleset))
# might also convert to tuple + check length to be super-certain
# however, maybe even better: define a function that deserialises _one_ ruleset, place for-loop in payload-code (no need to write a unittest for for-loop ;-))

assert isinstance(ruleset, CRRS)

assert len(ruleset.rules) == 3
rule1, rule2, rule3 = ruleset.rules
assert rule1.rescore == 'no-change' # btw: feel free to use dummy-values, such as "example-1", "example-2", etc
# also: some "sample-checks" should be enough. asamof, we might not actually want to test `dacite` in too much detail

# second test: add extra attributes (dacite will ignore those); e.g. by altering existing dict
ruleset_with_extra_attributes = ....
# deserialise + check again (maybe compare w/ previous value

# third test: use invalid value (e.g. a dict w/ missing attrs, or attrs of wrong type, or pass-in list instead of dict)
# again: we should not test dacite too much

```

2024-11-13 19:45 UTC, ccwienk commented on rescore/model.py
> -    TODO: publish rescoring-docs (removed SAP-internal reference prior to open-sourcing)
oof.. that comment did not age well 🙈

2024-11-14 08:11 UTC, zkdev commented on config.py
> +            rescore.model.CveRescoringRuleSet( #noqa:E1123
see [commit-msg](https://github.com/open-component-model/delivery-service/pull/237/commits/408283ca59f0563e790b0410b9821cf34902b3f6) :-)

2024-11-14 12:10 UTC, zkdev commented on rescore/model.py
> +    type: RuleSetType
Can we drop the `type` attribute entirely? 🤔 
We have type specific RuleSet classes, I do not see the need to explicitly set the type as class field.

Previously it made sense as it was used to differentiate RuleSets

2024-11-14 14:59 UTC, zkdev commented on rescore/model.py
> +    type: RuleSetType
Considering default configuration we discussed earlier:
We need a means to map type reference of a default rule set configuration to an instance of `RuleSet`.
If we would replace explicit value with `type(self)`, we would still need a mapping (e.g. `CveRescoringRuleSet` to `cve`).

Why not avoid this mapping by using type information in expected format directly, as suggested by this PR @ccwienk ?

2024-11-15 08:47 UTC, ccwienk commented on rescore/model.py
> +    type: RuleSetType
> Can we drop the type attribute entirely? 🤔
we might. this, however would have the drawback of requiring all Rule-Types to have pairwise unambiguous signatures, and it will make rulesets/rules in serialised (JSON/YAML) form less self-describing, and thus harder to understand by human readers (also, deserialisation will have to resort to black magic)
-> I do not think dropping `type` attr is a good idea

as for using an enum vs. the type itself: It is correct that we need a mapping between (Rule[Set]-)types and type-name (in serialised form) anyhow. However, my proposal would slightly reduce redundancy (DRY), as it would:
- delegate writing own type to base-class (so subclasses do not have to overwrite explicitly)
- use the type we already have, instead of adding another (external) value to describe the type

We might in fact even use the type's name (like so `type(self).__class__.__name__) for serialisation.

Admittedly, while removing some redundancy, this increased complexity, compared to using an external enum might not be adequate. Hence I will leave it up to you to decide whether or not to pickup my proposal.

2024-11-20 07:21 UTC, 8R0WNI3 commented on rescore/model.py
> +    raise ValueError('No default rule_set found for the specified type.')
nit: It might be helpful to also log the specified `default_rule_set_names` here. Btw, I think the name `DefaultRuleSetNames` is a little bit misleading as one instance only refers to one _name_ (!= _nameS_) and also considers the type. What about just calling it `DefaultRuleSet` or something?

2024-11-20 07:21 UTC, 8R0WNI3 commented on rescore/model.py
> +        if default_rule_set_name.type == rule_set_type:
nit: Rather use identity comparison `is` for enums.

2024-11-20 07:21 UTC, 8R0WNI3 commented on rescore/model.py
> +            and ruleset.type == default_rule_set_names.type
ditto (identity comparison)

2024-11-20 07:21 UTC, 8R0WNI3 commented on rescore/model.py
> +    raise ValueError('No default rule_set_name found for the specified type.')
Also here, it might be helpful to actual log the specified type.

2024-11-20 07:21 UTC, 8R0WNI3 commented on test/test_rescoring.py
> +import dacite
nit: Place import of `dacite` package in second import block:

```python3
# imports of packages included in Python standard library

# imports of third-party packages

# imports of thirt-party packages distributed by ourselves

# local imports
```

2024-11-20 07:21 UTC, 8R0WNI3 commented on test/test_rescoring.py
> +                'default': True,
I'm confused, do we plan to specify default rulesets via `defaultRuleSetNames` or via this flag now?

2024-11-20 07:21 UTC, 8R0WNI3 commented on test/test_rescoring.py
> +# deserializsation of rescoring rulesets
I think the function name is already self-describing :^)

2024-11-20 07:21 UTC, 8R0WNI3 commented on test/test_rescoring.py
> +            type=cve_rule_set_raw['type'],
Either don't specify the `type` here (the default value is already set) or convert it to the expected enum.

2024-11-20 07:21 UTC, 8R0WNI3 commented on test/test_rescoring.py
> +    assert rule1.rescore == rescore.model.Rescore.NO_CHANGE
ditto: identity comparison using `is` for enums

2024-11-20 07:21 UTC, 8R0WNI3 commented on test/test_rescoring.py
> +            type=cve_rule_set_raw['type'],
ditto

2024-11-20 07:21 UTC, 8R0WNI3 commented on rescore/artefacts.py
> +    rescoring_rule_set_lookup: CveRescoringRuleSetLookup,
We'll also have to adjust the `CveRescoringRuleSetLookup` type hint as it is actually not accurate anymore.

2024-11-20 08:49 UTC, TuanAnh17N commented on test/test_rescoring.py
> +                'default': True,
we initially considered specifying default rule sets using the default flag within each rule set. however, we decided to standardize on using defaultRuleSetNames for this purpose

2024-11-21 10:21 UTC, zkdev requested changes

2024-11-21 10:21 UTC, zkdev commented on features/__init__.py
> +        for item in rescoring_raw['defaultRuleSetNames']
nit: please use a more expressive name than `item`

2024-11-21 10:21 UTC, zkdev commented
just some nits remaining from my side, overall /lgtm

2024-11-21 13:52 UTC, zkdev approved these changes
/lgtm

2024-11-21 13:55 UTC, merged