Add compliance summary caching
open-component-model/delivery-service pull request #242
Opened 2024-11-11 10:34 UTC by 8R0WNI3

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

2024-11-11 12:01 UTC, ccwienk requested changes

2024-11-11 12:01 UTC, ccwienk commented on metadata.py
> +        # empty. In that case, the cache is invalidated upon successful finish of the scan.
should not we rather have this function _raise_ upon invalid parameters, and have the caller do special-case handling (as described in comment)?

2024-11-11 12:05 UTC, ccwienk commented on deliverydb/cache.py
> +          name: deleteAfter
should we also add a `staleAfter` parameter (semantics: mark as stale (after date) - similar to marking for deletion, but will keep entry, and return it marked as stale)

2024-11-11 12:25 UTC, 8R0WNI3 commented on deliverydb/util.py
> +        async for partition in rescorings_query.partitions(size=50)
I did not do any great analysis here, I just figured this value to be great enough to be able to handle common minor queries in one chunk while still not block in case of major queries 🤔

2024-11-11 12:30 UTC, 8R0WNI3 commented on metadata.py
> +        # empty. In that case, the cache is invalidated upon successful finish of the scan.
These are not really _invalid_ parameters, but rather _unsupported_ parameters, in that there will be for sure such findings which don't have these parameters set. And I'd like to avoid to pull this up since it's only a private function within this module and the special handling happens on BDBA extension side (separated from this module by a HTTP request).

2024-11-12 06:45 UTC, 8R0WNI3 commented on deliverydb/cache.py
> +          name: deleteAfter
Hmm I'm not sure if we should add a separate value for that or just use existing `deleteAfter` also for that purpose? More precisely, I think if the `deleteAfter` timestamp is due (but the entry was still not deleted yet), a client should be able to still retrieve that value with said "stale" flag and can choose to force re-calculate the value. Next to that, a caching-job should of course pick up those entries which should already be deleted and re-calculate them. Thinking about a `staleAfter` timestamp, I think the exact same semantics apply, don't they? So, unless you think of another difference between both of them, I think we can keep it more simple and just use the one parameter. Wdyt?

2024-11-12 07:38 UTC, ccwienk submitted a review, later dismissed

2024-11-12 12:31 UTC, merged