Add cache manager extension
open-component-model/delivery-service pull request #251
Opened 2024-11-19 15:10 UTC by 8R0WNI3

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

2024-11-20 10:36 UTC, TuanAnh17N commented on cache_manager.py
> +    def interval_min(column: sqlalchemy.DateTime) -> float:
should'nt the return type be `sqlalchemy.sql.elements.BinaryExpression` instead of `float`? the return value seems to be a sqlalchemy expression that gets evaluated in the db. i might be wrong tho

2024-11-20 10:36 UTC, TuanAnh17N commented on cache_manager.py
> +        return sqlalchemy.extract('epoch', (now - column)) / 60
what happens if 'column' is `NULL`? wouldnt this cause the sql expression (now - column) and sqlalchemy.extract to evaluate to `NULL`, potentially leading to unexptected behavior?

2024-11-20 10:36 UTC, TuanAnh17N commented on cache_manager.py
> +        logger.error(f'Cleaned {cleaned_size / 1000000}mb from cache')
shouldn't this log message use `logger.info`instead of `logger.error`? cleaning the cache seems like a normal operation, not an error condition.

2024-11-20 12:17 UTC, 8R0WNI3 commented on cache_manager.py
> +    def interval_min(column: sqlalchemy.DateTime) -> float:
You're absolutely right :-)

2024-11-20 12:18 UTC, 8R0WNI3 commented on cache_manager.py
> +        logger.error(f'Cleaned {cleaned_size / 1000000}mb from cache')
Ups, good catch! This is still a debugging artefact... I happen to play around with the log levels locally to easier focus 😅🫣

2024-11-21 08:33 UTC, zkdev commented on Dockerfile.extensions.cache-manager
> +ENTRYPOINT ["python3", "-m", "cache_manager"]
why not re-use the generic extension dockerfile and move the entrypoint to helm ?

2024-11-21 08:38 UTC, zkdev commented on cache_manager.py
> +async def clean_cache_if_exceeds(
nit: prefix with verb -> `clear_cache_if_exceeds`

2024-11-21 08:40 UTC, zkdev commented on cache_manager.py
> +    await cluster_relation(
we might want to migrate to postgres 17 and use vacuum instead, see https://www.postgresql.org/about/news/postgresql-17-released-2936/

2024-11-21 08:45 UTC, zkdev commented on config.py
> +class CacheCleanupStrategy:
please add brief doc str w.r.t. semantics (lower values means lower weight means less likely to cause a delete operation?)

2024-11-21 08:54 UTC, 8R0WNI3 commented on Dockerfile.extensions.cache-manager
> +ENTRYPOINT ["python3", "-m", "cache_manager"]
The generic extension Dockerfile is not sufficient here because it lacks postgresql functionality. Also, as this cache manager job will be extended to also prefill caches, it will need access to the Delivery-Service's sources. Hence, we _could_ combine it with existing Dockerfile for the service, however, I'm not sure if we should actually do so 🙈 Wdyt?

2024-11-21 09:18 UTC, ccwienk requested changes

2024-11-21 09:18 UTC, ccwienk commented on cache_manager.py
> +    logger.info(f'Current cache size: {size / 1000000}mb')
nit: I think `mega` prefix is commonly abreviated w/ `M` (upper-case), whereas lower-case `m` means `milli`

2024-11-21 09:18 UTC, ccwienk commented on cache_manager.py
> +    cleanable_size = size - cfg.max_buffer_bytes
naming-nit: reclaimable / prunable?

2024-11-21 09:18 UTC, ccwienk commented on cache_manager.py
> +        f'Will delete existing cache entries ({cleanable_size=}) until {cfg.max_buffer_bytes} '
naming: instead of buffer, we might rather call it cache (I think buffers typically refer to transient data-structures, like an in-memory-buffer for reading/writing chunks of data to/from)

2024-11-21 09:18 UTC, ccwienk commented on charts/extensions/charts/cache-manager/templates/cache-manager.yaml
> +  schedule: {{ default "0 * * * *" $.Values.schedule | quote }} # schedule may contain asterisks, quote to avoid yaml parser errors
nit: I think the (default) schedule _does_ contain asterisks :-)

2024-11-21 09:18 UTC, ccwienk commented on config.py
> +class CacheCleanupStrategy:
I think `strategy` is not a good fit. To me, a strategy might be something like `last-recently-used`, `fifo`, ..
how about calling this `CachePruningWeights` (or Params) instead?

2024-11-21 09:18 UTC, ccwienk commented on config.py
> +    :param int max_buffer_bytes:
I think using buffer and cache adjacently is misleading. how about either calling this `min_pruning_bytes` instead (which would define the minimum size below which no pruning will be done)?

2024-11-21 09:18 UTC, ccwienk commented on config.py
> +class CacheCleanupStrategy:
it might be nice to document what larger/smaller values mean semantically

2024-11-22 07:06 UTC, 8R0WNI3 commented on cache_manager.py
> +    '''
Dropped it in favour of reusing existing fs-space only upon new insertions. That way, it will also stay db-neutral.

2024-11-22 07:06 UTC, 8R0WNI3 commented on cache_manager.py
> +    await cluster_relation(
Dropped clustering at all (see other comment)

2024-11-22 13:48 UTC, ccwienk commented on Dockerfile.extensions.cache-manager
> +ENTRYPOINT ["python3", "-m", "cache_manager"]
different images have the benefit of making it easier to test changes (the more usage-scenario, the more things might break)

2024-11-22 13:55 UTC, ccwienk commented on Dockerfile.extensions.cache-manager
> +    py3-numpy \
can we make numpy/scipy optional dependencies? I think those are only required for responsibles-heuristics (btw, we should remove both packages anyhow, and use precalculated functions, rather than calculating them every time)

2024-11-22 13:55 UTC, ccwienk commented on Dockerfile.extensions.cache-manager
> +&& echo -e "[global]\nbreak-system-packages = true" >> $HOME/.config/pip/pip.conf \
should we add both python / pip + pip-cfg into base-image?

2024-11-22 13:55 UTC, ccwienk commented on cache_manager.py
> +import asyncio
a brief module-docstr explaining what cache-mgr does (prune cache ..) would be nice

2024-11-22 13:55 UTC, ccwienk commented on cache_manager.py
> +        sys.exit(0)
should we rather exit w/ exitcode !== 0?

2024-11-22 14:18 UTC, 8R0WNI3 commented on Dockerfile.extensions.cache-manager
> +&& echo -e "[global]\nbreak-system-packages = true" >> $HOME/.config/pip/pip.conf \
Done with https://github.com/gardener/cc-utils/commit/9b12ec990804a27f82dac6e55a9f54278282fbc1

2024-11-22 14:30 UTC, 8R0WNI3 commented on cache_manager.py
> +    logger.info(f'Max cache size: {bytes_to_str(cfg.max_cache_size_bytes)}')
I think that could also be something we could add to the delivery-service, i.e. adding information on cache hits/misses to prometheus.

2024-11-22 14:30 UTC, 8R0WNI3 commented on config.py
> +    should not be deleted. 0 means the property does not affect the priority for the next deletion.
Fine with me.

2024-11-25 09:52 UTC, zkdev requested changes
/lgtm

2024-11-25 09:52 UTC, zkdev commented on cache_manager.py
> +async def prune_cache(
I prefer to split "prune-required" check and actual pruning -> SoC

2024-11-25 10:37 UTC, ccwienk submitted a review, later dismissed

2024-11-25 14:09 UTC, merged