Enable simple github-asset based authorisation
open-component-model/delivery-service pull request #258
Opened 2024-11-21 14:48 UTC by zkdev

**What this PR does / why we need it**:
Expected github-asset list:
```
delivery-cfg:
  privileged_github_assets:
  - github.com/zkdev # username
  - github.com/open-component-model # organisation
  - github.com/open-component-model/maintainer # team
```

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

2024-11-22 06:33 UTC, 8R0WNI3 submitted a review, later dismissed
/lgtm

2024-11-22 06:33 UTC, 8R0WNI3 commented on middleware/auth.py
> +            if asset in delivery_cfg.privileged_github_assets():
I'm not sure about the placement of this configuration. Shouldn't we rather move it to `delivery_cfg.auth.privileged_github_assets`?

2024-11-22 13:41 UTC, ccwienk commented
as discussed earlier today, I suggest to already prepare this cfg to be more generic / extensible + RBAC-style. how about sth. like this (inspired from [k8s](https://kubernetes.io/docs/reference/access-authn-authz/rbac/)):

```
role-bindings:
- subjects:
    type: github-oauth # github-team | github-user?
    name: username # | teamname; we might also use fully qualified urls (e.g. github.com/gardener/core-team) instead
  roles:
  - admin
 ```

Shortcuts for first iteration:
- hardcode role(s) - e.g. use `admin` (or `root` | `superuser`) with "full-access"-semantics for now
- do not allow any other subjects than github

2024-11-26 11:59 UTC, zkdev commented on middleware/auth.py
> +            if asset in delivery_cfg.privileged_github_assets():
we can even go one step further and define assets / role-bindings per oauth cfg
this deduplicates oauth-hostname (e.g. github.com) on asset level

2024-11-27 07:09 UTC, 8R0WNI3 requested changes

2024-11-27 07:09 UTC, 8R0WNI3 commented on middleware/auth.py
> +        for role_binding in role_bindings:
Please factor out authorisation check into a separate function.

Also, I know we only want to support "admin" role for now, but wouldn't it make sense to already change logic here a bit to return list of assigned roles rather than something like a boolean? This would ease support for multiple roles afterwards.

2024-11-27 07:09 UTC, 8R0WNI3 commented on middleware/auth.py
> +    roles: list[str]
Let us already define an enum here for existing roles (although there will be only one shared role for now).

2024-11-27 09:22 UTC, ccwienk requested changes

2024-11-27 09:22 UTC, ccwienk commented on middleware/auth.py
> +                    cast=[SubjectType],
nit: you might tell dacite to cast `enum.Enum` (this will tell it to try to cast any enum, which might save some typing / adjustments upon later changes)

2024-11-27 09:22 UTC, ccwienk commented on middleware/auth.py
> +                if subject.type == SubjectType.github_user:
since you went through the length of defining enums, you should also use identity-comparison (`is`)

2024-11-27 09:22 UTC, ccwienk commented on middleware/auth.py
> +            break
I think using else/break in nested loops is not exactly easy to read. How about factoring out to a function (may be defined inline), and have the function use `return`, like so:

```
def find_subject(...):
  if <match>: return match

subject = find_subject(...)

if not subject:
  raise ..
```

2024-11-27 09:22 UTC, ccwienk commented on middleware/auth.py
> +            # assume there are only "admin" role bindings for now
I think we should already look explicitly for _a_ role (see my other comment below), and hardcode the role to admin.

this is more explicit, and will make it easier how / where code should be extended, once we have more roles.

2024-11-27 11:50 UTC, 8R0WNI3 submitted a review, later dismissed
/lgtm

2024-11-27 11:50 UTC, 8R0WNI3 commented on middleware/auth.py
> +                if subject.type is SubjectType.GITHUB_ORG:
nit: If you concatenated those conditions using `elif` instead, you'd not have to check against `subject.type` again if, for example, it is already clear that it's a GitHub user but the username does not match.

2024-11-29 14:30 UTC, merged