Add decompressor middleware
open-component-model/delivery-service pull request #26
Opened 2024-05-02 15:03 UTC by 8R0WNI3

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

2024-05-03 10:41 UTC, ccwienk requested changes

2024-05-03 10:41 UTC, ccwienk commented on middleware/decompressor.py
> +                decompressor = zlib.decompressobj(wbits=zlib.MAX_WBITS | 16)
not too sure about bitwise OR'ing MAX_WBITS and 16. Does this actually make it more obvious what this means? we might just as well write `31`, wdyt? :-/

2024-05-03 10:41 UTC, ccwienk commented on middleware/decompressor.py
> +        if req.get_header('Content-Encoding') == 'gzip':
I think we should also check for content-type -> only json-decode if we actually got json (otherwise, we might only do the uncompressing part).

While I did not check the contract defined for middleware in falcon too deeply: would it be an option for the middleware just to intercept the stream (so we might not even have to do json-decode)?

2024-05-03 10:41 UTC, ccwienk commented on middleware/decompressor.py
> +        if req.get_header('Content-Encoding') == 'gzip':
also (nit): I would prefer to incert logic (early-exit in case we do not want to modify a request)

2024-05-03 13:23 UTC, 8R0WNI3 commented on middleware/decompressor.py
> +        if req.get_header('Content-Encoding') == 'gzip':
As far as I can tell, the middleware is not supposed to intercept the stream, but just read it and put custom data into the `req.context` object.

2024-05-06 07:59 UTC, zkdev approved these changes
just some nits
overall /lgtm

2024-05-06 07:59 UTC, zkdev commented on middleware/decompressor.py
> +        if content_encoding == 'gzip':
nit: Introduce str-enum for known content encodings

2024-05-06 07:59 UTC, zkdev commented on middleware/decompressor.py
> +                raise falcon.HTTPBadRequest(title=f'Invalid gzip data; {e}')
exception `e` can be quite lengthy, probably better to add to HTTPBadRequest `description`, rather than `title`.

2024-05-06 09:49 UTC, ccwienk requested changes
+1 for cleanup. would you maybe push cleanup commit already to `master` to shrink this pull-request?

2024-05-06 09:49 UTC, ccwienk commented on middleware/decompressor.py
> +                data = decompressor.decompress(req.stream.read())
can we rather patch the stream (so we do not have to read the whole request into memory)?

2024-05-06 09:49 UTC, ccwienk commented on middleware/decompressor.py
> +        if req.get_header('Content-Type') == 'application/json':
nit: might use `content_type` attribute (set by falcon)?

2024-05-06 21:02 UTC, ccwienk commented on metadata.py
> +        body = req.context.media
is it not possible to patch `req.media`? :-(

2024-05-07 08:28 UTC, 8R0WNI3 commented on metadata.py
> +        body = req.context.media
Leider nicht ohne Weiteres 🙈 Dafür ist bei Falcon die `context` Property vorgesehen -> [ref](https://falcon.readthedocs.io/en/2.0.0/api/request_and_response.html#falcon.Request.context)

```
2024-05-07 10:21:36,917 [ERROR] TID:13640101888 __main__: Traceback (most recent call last):
  File "falcon/app.py", line 360, in falcon.app.App.__call__
  File "/Users/I538859/dev/github.com/delivery-service/middleware/decompressor.py", line 42, in process_resource
    req.media = data
    ^^^^^^^^^
AttributeError: property 'media' of 'Request' object has no setter
```

2024-05-08 10:53 UTC, 8R0WNI3 commented on middleware/decompressor.py
> +                data = decompressor.decompress(req.stream.read())
Unfortunately, I did not find a proper way of doing so using falcon :-(

2024-05-10 09:06 UTC, merged