Add pre-calculation of functions to cache manager
open-component-model/delivery-service pull request #260
Opened 2024-11-25 06:43 UTC by 8R0WNI3

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

2024-11-25 09:56 UTC, zkdev approved these changes
/lgtm

2024-11-25 09:56 UTC, ccwienk requested changes

2024-11-25 14:28 UTC, 8R0WNI3 commented on cache_manager.py
> +        await components_util.component_versions(
As discussed, will add a comment to the cached function that the cache manager job expects said function to use the delivery-db cache.

2024-11-25 15:15 UTC, 8R0WNI3 commented on cache_manager.py
> +async def prefill_component_versions_cache(
I did not come up with a cleaner structure than this while considering these two aspects:
- Some prefilling functions require the configured components to be processed recursively (i.e. compliance summaries should be calculated not only for the root component), whereas some functions may only require processing of the configured root component (i.e. the available components version are not required to be retrieved for the whole transient component tree).
- In the first case (-> recursion is desirable), it might be beneficial to deduplicate across multiple configured root components. Taking configured landscapes as root components as an example, it is common that they share a lot of component versions so there is no need to calculate the compliance summary for each component version in each landscape, but only once per component version.

Do you have a structure in mind which will take care of these aspects while increasing readability?

2024-11-27 08:51 UTC, ccwienk approved these changes

2024-11-27 09:12 UTC, merged