Do not try to stream if size is unknown
open-component-model/delivery-service pull request #262
Opened 2024-11-25 13:41 UTC by zkdev

local blob size is optional

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

2024-11-25 13:50 UTC, 8R0WNI3 commented on ocm_util.py
> +    content = blob.iter_content(chunk_size=4096),
Rather put this into the `else` block + remove trailing `,`

2024-11-25 15:33 UTC, 8R0WNI3 submitted a review, later dismissed
/lgtm

2024-11-25 16:50 UTC, ccwienk requested changes
while I agree that we unfortunately have to read the blob if caller does not pass size to us, I strongly object falling-back to in-memory (this is a potential source for oom-bugs)!
-> either raise ValueError, or fallback to tempfile
edit: see inline comment. I think we can be even smarter.

2024-11-28 06:47 UTC, 8R0WNI3 commented on ocm_util.py
> +        oci_blob_refs = mf.layers if isinstance(mf, oci.model.OciImageManifest) else mf.manifests
I'm not quite sure here, but wouldn't we also have to check `layers` of sub manifests in case it's an `OciImageManifestList` instead of checking against the digest of the sub manifests overall?

2024-11-28 07:55 UTC, zkdev commented on ocm_util.py
> +        oci_blob_refs = mf.layers if isinstance(mf, oci.model.OciImageManifest) else mf.manifests
Adjusted the code accordingly.
I was thinking whether we need to handle `ManifestList` case at all, as we are always checking component-descriptor oci-manifest. Not sure whether ocm-spec limits component-descriptor oci-manifest to just single arch 🤔.

2024-11-28 09:05 UTC, 8R0WNI3 approved these changes
/lgtm

2024-11-28 09:30 UTC, merged