Sast rescoring update
open-component-model/delivery-service pull request #270
Opened 2024-11-27 15:55 UTC by TuanAnh17N

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

2024-11-28 10:01 UTC, zkdev requested changes

2024-11-28 10:01 UTC, zkdev commented on cm06/scan.py
> +    main()
we might directly include the extension integration (k8s logging thread, cfg from k8s resource, ...)

2024-11-28 14:32 UTC, TuanAnh17N commented on test/test_rescoring.py
> +def sast_rescoring_rules_raw() -> dict:
i separated there fixtures to keep the rules distinctly organized and to allow for more targeted testing of individual rule sets. however, i wouldn't mind merging them

2024-11-29 14:56 UTC, ccwienk requested changes

2024-11-29 14:56 UTC, ccwienk commented on cm06/scan.py
> +    try:
at any rate, I think we can shortcut this kind of fine-granular exception-handling:

- open will already raise an exception (file-not-found) -> there is little benefit from printing "file-not-found", and re-raising it (just let `open` do its job, and let it raise..)
- ditto for JSONDE

2024-11-29 14:56 UTC, ccwienk commented on cm06/scan.py
> +        if label:
or better yet: invert:

```
for ....:
  if not (label := ...):
    continue
  if "second check":
    break
else:
  # not-found case
```

it might improve readability to factor-out "has_local" / "has_central" into (inline-defined) functions (working on _one_ source).

also, it should be noted that _each_ source-artefact should have an individual sast-status. typically, we will have exactle one source-artefact; however, we historically had cases where there were two (e.g. cc-utils used to declare two source-artefacts), and recently, we discovered a component with no source-artefacts.

2024-11-29 14:56 UTC, ccwienk commented on cm06/scan.py
> +def determine_component_context(
how about using the `relation`-attribute instead? I do not think we should hardcode such assumptions.

2024-11-29 14:56 UTC, ccwienk commented on cm06/scan.py
> +                and 'europe-docker_pkg_dev/gardener-project/' in image_reference
hardcoding such strs is a definite "no-no"

2024-11-29 14:56 UTC, ccwienk commented on rescore/model.py
> +class SastStatus(enum.StrEnum):
I think, alas, we will have a hard time to multiply-out all possible states. need to think still of a better proposal, though.

at least, I think we need to take cardinalities into account. such as:

```
- number of source-artefacts (as discussed: typically, but not always: 1, rarely: 0, even more rarely: 2 (but considering ocm, it can be any positive integer (or zero))
- "semantical rating" # okay / not okay
- mapping: <source-id>: <source-status> # no sast-linting, custom-sast-linting, central-sast-linting, both

btw, for the latter, maybe consider IntEnum? That way, we might use bit-oring and save us a fourth value

2024-12-02 15:30 UTC, zkdev commented on test/test_rescoring.py
> +def sast_rescoring_rules_raw() -> dict:
I don't mind either, if it makes things easier when can keep them separated :-)

2024-12-03 08:54 UTC, 8R0WNI3 requested changes

2024-12-03 08:54 UTC, 8R0WNI3 commented on cm06/scan.py
> +    cm06_config,
nit: Add type hints

2024-12-03 08:54 UTC, 8R0WNI3 commented on cm06/scan.py
> +    start_date = cm06_config.audit_start_date or datetime.date.today()
`audit_start_date` already defaults to today in `config.py`, so there should be no need to set it here (again).

2024-12-03 08:54 UTC, 8R0WNI3 commented on cm06/scan.py
> +    if cm06_config.audit_timerange_months:
`audit_timerange_months` also has a default value, so there should be no need for this condition here, should it?

2024-12-03 08:54 UTC, 8R0WNI3 commented on cm06/scan.py
> +        component_nodes = list(
nit: Since it's only iterated once over `component_nodes`, you don't have to explicitly convert it to a list.

2024-12-03 08:54 UTC, 8R0WNI3 commented on cm06/scan.py
> +                data=data_field
We'll have to set the `discovery_date` here as well to keep track of SLAs.

2024-12-03 11:49 UTC, ccwienk commented on config.py
> +    audit_timerange_months: int | None = None
+1

2024-12-11 09:20 UTC, ccwienk requested changes

2024-12-11 09:20 UTC, ccwienk commented on cm06/scan.py
> +import semver
mv semver to second import-block

2024-12-11 09:20 UTC, ccwienk commented on cm06/scan.py
> +        if label := source.find_label(name=dso.labels.SourceScanLabel.name):
codestyle: invert logic to decrease nesting/indentation:

```
for ...:
 if not (label := ...):
   continue
  # logic for label-handling goes here
```

2024-12-11 09:20 UTC, ccwienk commented on cm06/scan.py
> +                return True
semantically, this does not match the function's name.

if there is a skip-label, the component declares that no central linting is necessary. naming this function "has_central_linter" does not seem like a good match to me.

2024-12-11 09:20 UTC, ccwienk commented on cm06/scan.py
> +def deserialise_cm06_configuration(
cm06 is a sap-specific ID. rather call it SAST-Cfg/SAST_Policy_Cfg or the like.

2024-12-11 09:20 UTC, ccwienk commented on cm06/scan.py
> +        sys.exit(0)
rather consider this an error. also, preferably raise an exception, rather than using sys.exit

2024-12-11 09:20 UTC, ccwienk commented on cm06/scan.py
> +def get_landscape_versions(
this name is misleading. the function will enumerate component-versions of a given component in a given timerange. this will work for any ocm-component, regardless of whether or not they represent a landscape, hence the function's name should reflect this.

2024-12-11 09:20 UTC, ccwienk commented on cm06/scan.py
> +def create_no_linter_finding(
naming: rather name this `create_missing_linter_finding`. w/ current name, the name might suggest the function does not create a linter-finding, which I consider to be somewhat confusing

2024-12-11 09:20 UTC, ccwienk commented on cm06/scan.py
> +        help='specify kubernetes cluster to interact with',
nit: you might omit `specify`. it is obvious for any parameter passed via ARGV that it is used to specify something. stating so does not actually add any valuable information.

2024-12-11 09:20 UTC, ccwienk commented on cm06/scan.py
> +        help='specify kubernetes cluster namespace to interact with',
could you be more specific as to what "interact with" means? maybe it would be more precise to just replace `interact with` by `use`.

2024-12-11 09:20 UTC, ccwienk commented on cm06/scan.py
> +            specify the context the process should run in, not relevant for the artefact
how do `--cfg-name` and `--k8s-cfg-name` relate to each other? which type of cfg is referenced by _this_ one? what context is meant here (by "there are context independent")?

2024-12-11 09:20 UTC, ccwienk commented on cm06/scan.py
> +        default=os.environ.get('CFG_NAME'),
general remark: (why) do we need reading defaults from env? is this a convenience-feature for local development? if so, maybe we should consider optionally reading from a cfg-file instead (I do not have a strong objection against honouring env-vars, though)

2024-12-11 09:20 UTC, ccwienk commented on cm06/scan.py
> +        '--delivery-service-url',
since specifying this will overwrite, maybe we should reflect this in parameter-name. is this intended for dev-setups?

2024-12-11 15:22 UTC, TuanAnh17N commented on cm06/scan.py
> +            specify the context the process should run in, not relevant for the artefact
`--k8s-cfg-name` arg is used to specify the k8s config, which includes credentials need to authenticate and interact with the k8s API server.
`--cfg-name` arg refers to the scan config, which contains settings related to the scanning process, such as SAST config & co.

it may be a good idea to rename `--cfg-name` to something more descriptive, such as `--scan-cfg-name` or smth like that

2024-12-12 08:25 UTC, zkdev commented on cm06/scan.py
> +        default=os.environ.get('CFG_NAME'),
while env vars can of course be used for local dev setup, their main purpose is k8s deployment itself
we use env vars in pod spec to pass arguments to pods, e.g. see [bdba extension](https://github.com/open-component-model/delivery-service/blob/06f6b4d27d88185f305f2c8ac410970ae9773233/charts/extensions/charts/backlog-controller/templates/bdba.yaml#L37)

2024-12-12 08:40 UTC, zkdev requested changes

2024-12-12 08:40 UTC, zkdev commented on cm06/scan.py
> +    landscape_versions = get_component_versions(
nit: the "context component" isn't necessarily a landscape, please use a more universal variable name

2024-12-12 08:40 UTC, zkdev commented on cm06/scan.py
> +        component_nodes = cnudie.iter.iter(
rather inline in for-loop
`cnudie.iter.iter` returns a generator, which can only be traversed once
using a variable indicates it could be re-used which might lead to bugs

2024-12-12 08:40 UTC, zkdev commented on config.py
> +    CM06 = 'cm06'
Can we use a more generic name, like `sastLintCheck`?

2024-12-12 08:40 UTC, zkdev commented on config.py
> +            if rule_set_raw['type'] == rescore.model.RuleSetType.CVE
should this really be part of this PR?

2024-12-12 08:40 UTC, zkdev commented on rescore/model.py
> +    BLOCKER = 'blocker'
be consistent with `to-` prefix, I suggest to use `to-blocker`

this will also help to differentiate whether a rescoring maps directly to a value, or needs to be interpreted further (like `reduce`)

2024-12-12 08:40 UTC, zkdev commented on rescore/model.py
> +            sub_types=rule.get('sub-types', []),
should we use these fallback values as default values on dataclass level?

2024-12-12 08:40 UTC, zkdev commented on rescore/utility.py
> +def rescore_sast_severity(
this function should work for all types of rescoring-rule no?
can we merge / factor out with existing bdba rescoring?

2024-12-12 08:40 UTC, zkdev commented on test/test_rescoring.py
> +                        'match': [{'component-name': 'github.wdf.sap.corp/.*'}],
use a less specific dummy value for tests, please

2024-12-12 09:24 UTC, 8R0WNI3 requested changes

2024-12-12 09:24 UTC, 8R0WNI3 commented on rescore/utility.py
> +) -> str:
If this method should return a `str` (as declared in the type hint), you'll have to return either `...Severity.BLOCKER.name` or `...Severity.NONE.name`.

2024-12-12 09:24 UTC, 8R0WNI3 commented on rescore/utility.py
> +            if re.match(condition['component-name'], finding.artefact.component_name):
As we require each `condition` within `rescoring_rule.match` to define a `component_name` (again, let us rather use snake_case consistently), rather define this also model-wise instead of allowing arbitrary dictionaries.

2024-12-12 09:24 UTC, 8R0WNI3 commented on rescore/utility.py
> +                    return rescoring_rule
I think we'll also have to check for matching `sast_status`, don't we? 🤔

2024-12-12 09:24 UTC, 8R0WNI3 commented on rescore/utility.py
> +                last_update=datetime.datetime.now(datetime.timezone.utc),
nit: Defining `datetime.datetime.now` once for the whole iteration has the benefit that it is easier (or possible) to conclude whether or not rescorings were created during the same execution or in different ones (-> this was for example necessary to be able to detect our missing idempotence in the past).

2024-12-12 09:24 UTC, 8R0WNI3 commented on rescore/utility.py
> +                severity=rescore_sast_severity(
I think we should also check whether the rescored severity actually differs from the current one. If not, we don't have to create a rescoring.

2024-12-12 09:24 UTC, 8R0WNI3 commented on cm06/scan.py
> +        if not (label := source.find_label(name=dso.labels.SourceScanLabel.name)):
According to the [documentation](https://pages.github.tools.sap/kubernetes/compliance-reporting/ocm-labels/scanning-hints-source-analysis.html#id1), the skip-scan label may also be declared on component level (as opposed to source level). I think we should also consider that case 🤔

2024-12-12 09:24 UTC, 8R0WNI3 commented on cm06/scan.py
> +    if cm06_config.component_version and cm06_config.audit_timerange_days:
I think `audit_timerange_days` is always configured since it defines a default value, isn't it?

2024-12-12 09:24 UTC, 8R0WNI3 commented on cm06/scan.py
> +    landscape_versions = get_component_versions(
Also here, these don't have to be _landscape_-versions, but it depends on what is configured for the extension. Why not simply use `component_versions` instead?

2024-12-12 09:24 UTC, 8R0WNI3 commented on cm06/scan.py
> +                    discovery_date=time_now,
`discovery_date` expects `datetime.date` instead of `datetime.datetime`

2024-12-12 09:24 UTC, 8R0WNI3 commented on cm06/scan.py
> +        discovery_date=time_now,
ditto: `datetime.datetime` -> `datetime.date`

2024-12-12 09:24 UTC, 8R0WNI3 commented on cm06/scan.py
> +            component_context=component_name,
I think `component_context` is not required anymore at all, is it? Since `match` compares against the `component_name` already, this extra attribute is obsolete is suppose.

2024-12-12 09:24 UTC, 8R0WNI3 commented on cm06/scan.py
> +            for ruleset in cm06_config.sast_rescoring_ruleset:
`sast_rescoring_ruleset` is only a single ruleset and not iterable or am I wrong?

2024-12-16 15:27 UTC, zkdev requested changes

2024-12-16 15:27 UTC, zkdev commented on cm06/scan.py
> +        raise ValueError(
mv this check to caller (KISS + SoC)

2024-12-16 15:27 UTC, zkdev commented on rescore/utility.py
> -    rescoring_rules: typing.Iterable[rescore.model.CveRescoringRule],
shouldn't this match function remain rule-type specific?

2024-12-16 15:27 UTC, zkdev commented on rescore/utility.py
> +        if finding.data.severity == rescore_sast_severity(
deduplicate rescore func call

2024-12-16 15:33 UTC, TuanAnh17N commented on rescore/utility.py
> -    rescoring_rules: typing.Iterable[rescore.model.CveRescoringRule],
oh, mb - i mixed up the function

2024-12-16 16:29 UTC, TuanAnh17N commented on cm06/scan.py
> +        raise ValueError(
now that i think about it, i dont think we need that check anymore, since `audit_timerange_days` already has a default value. if a `component_version` is provided, we can simply return it, and if not, the logic for audit_timerage_days will take care of the versioning automatically

2024-12-17 11:42 UTC, ccwienk commented
@TuanAnh17N : I assume test-errors stem from dependency against (unreleased) changes in cc-utils? If so, then I suggest to first merge and release change for cc-utils + rerun tests here to be sure.

2024-12-17 12:16 UTC, ccwienk requested changes

2024-12-17 12:16 UTC, ccwienk commented on cm06/scan.py
> +def is_central_linter_ignored(
alas, I still am not too happy with the function's name. considering the signature, I think this function suggests that it will answer whether or not the passed-in component ignores "central linter". Which is not the intended semantics.

What this function _does_: it inspects the passed-in component for hints (via labels) indicating whether or not its source-artefacts should be subject to being scanned by sast-scanners.

At any rate, I think the function ought to be split into two:
- one that will return either the most specific scan-label(s) (*)
- one that will interpret scan-policy

As for the first part, I think you should invert precedence. If a component declares a source-scan-label at both component- and source-level, the label for source-artefact is more specific and should overwrite label at component-level.

We currently have only two cases:
- no source-artefacts
- exactly one source-artefact

While this makes things slightly easier, it is not nice to ignore the case of having more than one source-artefact. After some pondering, I think we should probably change reporting (again) and include source-artefacts.

So items to report would be `{component-name}:{component-version}/{source-id}`. In the vast majority of our BoM, this will make no difference w.r.t. amount of issues, etc.. However, it will implicitly cause components w/o sources to nicely be ignored without special-case-handling, which I think it nice, while at the same time also work for (future?) cases of components with multiple source-artefacts (which, as said, is allowed by OCM)

2024-12-17 12:16 UTC, ccwienk commented on cm06/scan.py
> +    return delivery_client.greatest_component_versions(
I think it is somewhat convoluted to use deliveryservice-client here. esp. considering the delivery-service-client is from cc-utils-repository, will call delivery-service, which in turn uses cnudie.retrieve(_async), again from cc-utils.

Anyhow, if I am not mistaken, said method has a `max_versions`-param defaulting to `5`, which does not seem like a good combination w/ timerange potentially encompassing more than 5 versions.

I think it might make more sense to have a function that will work like `cnudie.iter.iter`, but will start from versions for a root-component (I think this is how _this_ function is intended to be used?).

Preferably wrap underlying lookups w/ db-cached-decorator that was nicely crafted by @8R0WNI3 , rather than use delivery-service-client (note: db-caching will obviously only work within delivery-gear-k8s-cluster, so you might want to add a codepath for usage out of k8s-cluster; e.g. locally, or in pipeline).

/cc @8R0WNI3 | @zkdev : fyi - I think we should revisit this general topic (usage of delivery-svs vs. reusing API; I personally tend very strongly to avoiding the complexity and overhead of calling our own API via http)

2024-12-17 12:16 UTC, ccwienk commented on features/__init__.py
> +        if rule_set_raw['type'] == rm.RuleSetType.SAST
nit: use `is` (identity-comparison) for enum-values.

2024-12-17 12:16 UTC, ccwienk commented on test/test_rescoring.py
> +        if sast_rule_set_raw['type'] == rescore.model.RuleSetType.SAST
identity-comparison

2024-12-20 08:30 UTC, zkdev requested changes

2024-12-20 08:30 UTC, zkdev commented on cm06/scan.py
> +    if sast_config.component_version:
mv to caller, this function should only get versions from time range -> SoC
also, can we please use a more meaningful function name, e.g. `version_from_time_range`?

2024-12-20 08:30 UTC, zkdev commented on cm06/scan.py
> +    version_lookup = lookups.init_version_lookup()
rather pass in version-lookup (dependency injection)

2024-12-20 08:30 UTC, zkdev commented on cm06/scan.py
> +        )).prerelease and not pv.build
version filtering is good, but I suggest to at least make it configurable via function parameters

2024-12-20 08:30 UTC, zkdev commented on cm06/scan.py
> +        in filter_by_date_range(versions)
rather use built-in [filter function](https://docs.python.org/3/library/functions.html#filter)

2024-12-20 08:30 UTC, zkdev commented on cm06/scan.py
> +                continue
please add a brief comment explaining why this case is skipped to help our future selves x)

2024-12-20 08:30 UTC, zkdev commented on cm06/scan.py
> +                    path=(cnudie.iter.NodePathEntry(cnode.component),),
rather directly iter source nodes (node_filter in `cnudie.iter.iter`)

also, if constructing source_node manually, make sure to give the full path and not only the parent component

2024-12-20 08:30 UTC, zkdev commented on cm06/scan.py
> +                new_metadata.extend(rescored_metadata)
TIL: list.extend resolves a generator :-)

2024-12-20 08:30 UTC, zkdev commented on rescore/utility.py
> +def rescore_sast_severity(
it seems you decided against my suggestion, which of course is fine, but could you please elaborate what lead to this decision?

looking only at the PR I do not see a good reason against 🤔

2024-12-20 10:28 UTC, ccwienk requested changes

2024-12-20 10:28 UTC, ccwienk commented on cm06/scan.py
> +    version_lookup = lookups.init_version_lookup()
also: consistency (why pass-in component-descriptor-lookup, but not version-lookup)

2024-12-20 10:28 UTC, ccwienk commented on cm06/scan.py
> +        )).prerelease and not pv.build
I think we have a util-function for that in cc-util's `version.py` (at least `is_final` comes to my mind)

2024-12-20 10:28 UTC, ccwienk commented on cm06/scan.py
> +                continue
also: why not simply use note_filter.cnudie.iter.Filter.sources?`

2024-12-20 10:28 UTC, ccwienk commented on cm06/scan.py
> +                    path=(cnudie.iter.NodePathEntry(cnode.component),),
I think in this context, if is not a good idea to manually construct  sourcenodes.

2024-12-20 10:28 UTC, ccwienk commented on cm06/scan.py
> +                new_metadata.extend(rescored_metadata)
sure - it accepts any iterable (which includes generators)

2024-12-20 10:28 UTC, ccwienk commented on config.py
> +    component_name: str
rather accept a list of components, or "component-version-yielders"

2024-12-20 10:28 UTC, ccwienk commented on rescore/utility.py
> +        return github.compliance.model.Severity.NONE.name
make those enums `StrEnums` (if not already the case) + prefer using enum-values of str-values

2024-12-20 10:28 UTC, ccwienk commented on rescore/utility.py
> +    raise NotImplementedError(rescoring_rule.rescore)
nit: while we do use NIE for that in our "heritage" codebase, it is actually not intended to be used for this purpose (python-documentation states NIE is intended for being raised by (abstract) methods that were not implemented). rather use ValueError

2024-12-20 10:28 UTC, ccwienk commented on rescore/utility.py
> +        matching_rule = next(
I really do not like this pattern. how about rather doing sth. like

```
try:
 mr = next(...)
except StopIteration:
  continue
 ```

In my opinion, this makes it a lot more obvious what is being done.

2024-12-20 10:28 UTC, ccwienk commented on rescore/utility.py
> +            matching_sast_rescore_rule(
btw: is this function intended to yield more than one rule (judging from the name, I would assume: no)? if not, why not have the function either return a rule or None. This would make it less messy to use.

2024-12-20 10:28 UTC, ccwienk commented on rescore/utility.py
> +        if finding.data.severity == new_severity:
if severity is an enum (did not check), use `is` for comparison.

2024-12-20 10:28 UTC, ccwienk commented on rescore/utility.py
> +                comment='Automatically rescored based on rules.',
include rulename(s) (+ ruleset-name) in comment?

2025-01-08 11:32 UTC, zkdev commented on cm06/scan.py
> +import version as versionutil
what is the motivation behind this alias?

2025-01-08 11:34 UTC, zkdev commented on cm06/scan.py
> +def resolve_scan_policy(
I prefer `find` prefix as it is more meaningful

2025-01-08 11:35 UTC, zkdev commented on cm06/scan.py
> +def is_central_scan_skipped(
resolve this function and inline

dependency-injection -> scan-policy should be passed directly; only the is SKIP check remains

2025-01-08 11:37 UTC, zkdev commented on config.py
> +        default_value=365,  # Default range in days if not provided
omit comment, does not add value

2025-01-08 11:38 UTC, zkdev commented on config.py
> +    # Deserialize rescoring rules
can also be omitted, the invoked function in the next line has a meaningful name already, `deserialise_`

2025-01-08 11:40 UTC, zkdev commented on rescore/utility.py
> +    severity = ''
we should not default to empty str
rather let this function return the gcm.Severity enum and only deserialise the moment it is required

2025-01-08 11:43 UTC, zkdev commented on rescore/utility.py
> +        except StopIteration:
I do not think this is required, if generator does not yield a single element `list(generator)` will return empty list

2025-01-08 13:50 UTC, 8R0WNI3 requested changes

2025-01-08 13:50 UTC, 8R0WNI3 commented on cm06/scan.py
> +    version_lookup: collections.abc.Callable[[ocm.ComponentIdentity], list[str]],
There is already a predefined type hint available for `version_lookup` -> `cnudie.retrieve.VersionLookupByComponent`

2025-01-08 13:50 UTC, 8R0WNI3 commented on cm06/scan.py
> +    filter_final_only: bool = True,
This filter is not used, is it?

2025-01-08 13:50 UTC, 8R0WNI3 commented on cm06/scan.py
> +        return end_date.strftime('%Y-%m-%d') <= creation_date <= start_date.strftime('%Y-%m-%d')
I think there is no need to convert all of these dates to strings

2025-01-08 13:50 UTC, 8R0WNI3 commented on cm06/scan.py
> +                artefact_type=source.type,
Don't we have to also consider `artefact_kind`, `source.version` and `source.extraIdentity` here?

2025-01-08 13:50 UTC, 8R0WNI3 commented on cm06/scan.py
> +            severity=github.compliance.model.Severity.BLOCKER,
`severity` expects a string here, and since `Severity` is an integer enum, you'd have to use `BLOCKER.name`.

2025-01-08 13:50 UTC, 8R0WNI3 commented on cm06/scan.py
> +                if not snode.component.sources:
As you've already added the `node_filter` for sources, you can omit this check here because there will be only source nodes and every source node must have, well, a source.

2025-01-08 13:50 UTC, 8R0WNI3 commented on cm06/scan.py
> +                for source in snode.component.sources:
You can also omit the loop here (but keep its content of course), because if a component has multiple sources, `cnudie.iter.iter` will already yield multiple source nodes.

2025-01-08 13:50 UTC, 8R0WNI3 commented on cm06/scan.py
> +                                    artefact_type=source.type,
ditto: Don't we need artefact_kind + version + extraIdentity here as well?

2025-01-08 13:50 UTC, 8R0WNI3 commented on cm06/scan.py
> +                            username='sast-extension-auto-rescoring'
We might as well declare an extension specific type here to prevent duplicates, e.g. something like `sast-extension-user`.

2025-01-08 13:50 UTC, 8R0WNI3 commented on config.py
> +    :param str component_name:
This comment does not match the declared properties (anymore), you probable referred to `components`? Also, if we allow a list of component _names_, we must also allow dedicated component versions instead of only one version for all component names. You might as well reuse existing `config.Component` model class if it is suitable.

2025-01-08 13:50 UTC, 8R0WNI3 commented on rescore/model.py
> +    default_rule_set_raw = next(
I think this `next` expression is quite hard to read for the semantics to find the first element in a list matching a condition and else raise. What about:

```python
for default_rule_set_raw in rescoring_cfg_raw['defaultRuleSetNames']:
   if default_rule_set_raw['type'] == rule_set_type:
      break
else:
   raise ValueError(f'No default rule set found for {rule_set_type=}.')
```

2025-01-08 13:50 UTC, 8R0WNI3 commented on rescore/utility.py
> +    for rule in rescoring_rules:
Is it actually desirable to have multiple matching rescoring rules for one component? In that case like it is implemented now, always the last rule would "win" and the other ones would be ignored. I think it might be more obvious to follow if an exception would be raised in case multiple rules would match, and afterwards only work with one rule (i.e. drop the loop here).

2025-01-08 13:50 UTC, 8R0WNI3 commented on rescore/utility.py
> +                comment=f'Automatically rescored based on rules: {matching_rules_names}',
To not overflow the comment, we might drop the parameter `matching_rules_names` from the comment here as it is already persisted by `matching_rules`.

2025-01-09 09:09 UTC, zkdev commented on rescore/utility.py
> +    for rule in rescoring_rules:
I think we should allow multiple matching rules. This is already implemented for BDBA, but with severity-reduce rather than severity-to semantics.
Also, in near future I suggest to merge BDBA rescoring function and SAST rescoring function. For this PR I think it is fine to separate them as this will probably involve some more cross-repository interaction and refactorings / renamings.

2025-01-09 09:17 UTC, 8R0WNI3 commented on rescore/utility.py
> +    for rule in rescoring_rules:
I see your point, but as you also mentioned, in BDBA we have severity-reduce semantics, which means that multiple rules may add up to each other. In contrast, here we only have severity-to which erases each other in case multiple rules match, so in that case we have to decide on a rule how to determine the rule which is to be used (right now, the last matching rule always wins, if this is our desired state, it's fine to me to keep code as-is).

2025-01-09 15:44 UTC, 8R0WNI3 commented on cm06/scan.py
> +import features
The `features` module is currently only available in the `ocm-gear-service` package and not part of `ocm-gear-extensions`, and it should probably stay that way since it depends on other delivery-service specific modules, e.g. `middlewares`. Since the import is only required here for `VersionFilter`, I'd rather suggest to move `VersionFilter` from the `features` module to for example `config.py`, which is already a shared module.

2025-01-09 15:44 UTC, 8R0WNI3 commented on cm06/scan.py
> +            version_lookup=lookups.init_version_lookup(),
Since `component.version_filter` is already available now and `fetch_all_versions` also allows passing of such a filter, you should probably pass it here as well :^)

2025-01-09 15:44 UTC, 8R0WNI3 commented on rescore/model.py
> +    BLOCKER = 'to-blocker'
To be more consistent here, rather rename to `TO_BLOCKER = 'to-blocker'`

2025-01-10 10:19 UTC, zkdev requested changes

2025-01-10 10:19 UTC, zkdev commented on rescore/model.py
> +    rule_set_class: RuleSet,
rather name this `rule_set_ctor` to better fit semantics, could also be helpful for future use-cases where one wants to provide parameters from outside, e.g.:
```
rule_set_ctor = functools.partial(
  model.SASTRuleSet,
  foo='foo',
)

deserialise_default_rule_set(rule_set_ctor=rule_set_ctor, ...)
```

2025-01-10 10:19 UTC, zkdev commented on rescore/model.py
> +    rules_from_dict_method: collections.abc.Callable[
`_method` does not add real value as its type is already define in typehint (just think how bizarre it would be to name a variable like `name_str: str`)

also, iff we can set a meaningful default - please do so :-)

2025-01-10 10:19 UTC, zkdev commented on rescore/model.py
> +    return find_default_rule_set_for_type_and_name(
I think this should not be included in deserialisation function.
`default_rule_set` is the deserialised rule-set, thus the expected outcome of this function.
Rather let user(s) decide on their lookup strategy.

2025-01-10 10:19 UTC, zkdev commented on rescore/model.py
> +        yield SastRescoringRule(
can we use `dacite` instead?

2025-01-10 10:19 UTC, zkdev commented on rescore/utility.py
> +            severity = github.compliance.model.Severity.BLOCKER
rather also return on `TO_BLOCKER` to have clear semantics (first matching rule wins), please also add this info in a brief doc str

2025-01-13 09:01 UTC, zkdev requested changes

2025-01-13 10:27 UTC, ccwienk requested changes

2025-01-13 10:27 UTC, ccwienk commented on cm06/scan.py
> +) -> list[str]:
a docstr would be nice to explain how the function is intended to be used.

for example, I assume the function expects passed-in versions to be sorted; presumably, the function will return up to `max_versions_limit` greatest versions (<= greatest_version). If this is correct, then a good docstr should state this

in addition, if greatest_version may be "falsy", either add a default-value (e.g. greatest_version=None), and/or state what passing-in of greatest_version means.

2025-01-13 10:27 UTC, ccwienk commented on cm06/scan.py
> +    source: ocm.Source,
would it make sense to pass-in a SourceNode (and thus have a single object for (component-version, source))?

2025-01-13 10:27 UTC, ccwienk commented on cm06/scan.py
> +            severity=github.compliance.model.Severity.BLOCKER.name,
do we need severity to be UPPER-cased? if not, it would be sufficient to use `str(severity_value)`. depending on enum-value's symbolic names (rather than their value) is slightly dangerous, as one might be intrigued to change such names during refactorings

2025-01-13 10:27 UTC, ccwienk commented on cm06/scan.py
> +            component_versions = limit_versions(
else-case means there is no timerange configured? as this will not scale well, I suggest to drop this codepath and require a timerange to be configured (we might allow a special value, such as `-1` for "unlimited" later, if needed (which I doubt)).

2025-01-13 10:27 UTC, ccwienk commented on cm06/scan.py
> +                max_versions_limit=component.max_versions_limit,
naming: I think it is redundant to use both `max` and `limit`. alternatives:

- max_versions
- versions_limit

2025-01-13 10:27 UTC, ccwienk commented on cm06/scan.py
> +        for component_version in sorted(component_versions, key=semver.VersionInfo.parse):
use `version.parse_to_semver` (-> using semver module directly will be stricter than OCM allows ("relaxed semver"), which is a bug).

2025-01-13 10:27 UTC, ccwienk commented on config.py
> +    components: tuple[Component]
while this is correct, we might also consider using `list` for dataclasses which we serialise to/from JSON/YAML (as at least JSON has no support to discriminate between tuple and list (array in JSON's terms)).

2025-01-13 10:27 UTC, ccwienk commented on features/__init__.py
> +        if rule_set_raw['type'] is rm.RuleSetType.SAST.value
unless `value` is actually an enum-value, you should _not_ use identity-comparison. I assume RuleSetType is a StrEnum? In that case, `value` is of type `str`. while in most cases, identity-comparison will yield the correct result, it is not semantically correct to use identity-comparison.

I think the best approach (which will also check `type` to be a known enum), is the following:

```
if RuleSetType(rule_set_raw['type']) is RuleSetType.SAST: ...
```
This leverages enum's default initialiser, which will convert str -> enum-value. Note that this will raise ValueError for values that are not valid RST-values (so explicit error-handling might be needed).

2025-01-13 10:27 UTC, ccwienk commented on rescore/model.py
> +        if default_rule_set_raw['type'] == rule_set_type:
also, please be consistent w/ enum-handling / comparison. can't we delegate deserialisation of RuleSets to `dacite` (so we do not have to operate on the "raw" dicts?

2025-01-13 10:27 UTC, ccwienk commented on rescore/utility.py
> +def matching_sast_rescore_rules(
naming-nit: I think we should rather call this `rescorING_rules` (UPPER-case for highlighting - please do not use upper-case like that, of course).

this will also make it easier to discriminate:
- rescoring-rules vs
- rescore (the operation of actually doing a rescoring)

2025-01-13 10:27 UTC, ccwienk commented on test/test_rescoring.py
> +        if cve_rule_set_raw['type'] is rescore.model.RuleSetType.CVE.value
see above. please consistently use identity-comparison:
- if comparing enum-values
- if comparing global singleton-values (True, False, None, ..)
- if otherwise needing to check for object-identity (e.g. for sentry-values)

in all other cases (the vast majority), use __eq__ / `==`

for reference, see: 
https://docs.python.org/3/reference/expressions.html#value-comparisons
https://docs.python.org/3/reference/expressions.html#is-not

2025-01-13 10:28 UTC, ccwienk commented on cm06/scan.py
> +import features
good catch. we might (if not already the case) add some (brief) module-docstrs explaining intended usage, as this might not be obvious.

2025-01-13 10:28 UTC, ccwienk commented on rescore/model.py
>  class Rescore(enum.Enum):
not related to this pullrequest. however: use StrEnum?

2025-01-16 09:05 UTC, zkdev commented on cm06/scan.py
> +                        for src_ref in (resource.srcRefs or [])
please check against `ocm/__init__.py`

2025-01-16 09:07 UTC, zkdev commented on cm06/scan.py
> +                        if src_ref.identitySelector.get('name') == snode.source.name
add brief comment to hint on current limitation (~ only support identity selector for now)

2025-01-16 09:08 UTC, zkdev commented on cm06/scan.py
> +                resources = (
rather move to dedicated function, it is hard to read

2025-01-16 09:10 UTC, zkdev commented on cm06/scan.py
> +                if not all_findings_for_rescoring or not sast_config.sast_rescoring_ruleset:
nit: rather use one condition per line

2025-01-16 09:11 UTC, zkdev commented on cm06/scan.py
> +                if not all_findings_for_rescoring or not sast_config.sast_rescoring_ruleset:
also, add scan-info later to avoid duplicate lists

2025-01-16 09:12 UTC, zkdev commented on cm06/scan.py
> +    for component in sast_config.components:
I think this might be a good candidate to move to a generator function

2025-01-21 13:20 UTC, zkdev requested changes

2025-01-21 13:20 UTC, zkdev commented on cm06/scan.py
> +def iter_sast_metadata(
I suggest to restructure this function.
- iter over sast_config.components on top level
- mv component_versions check also to top level, and factor our component_version_fetch logic to function
- mv source node iteration to dedicated function (yields artefact-metadata)

rational:
this function does too many things (SoC). also, nested loops and chained ifs are really hard to follow, especially if a function stretches over 150 lines

2025-01-21 13:20 UTC, zkdev commented on cm06/scan.py
> +            time_now=time_now,
rather name this parameter (creation_)timestamp and leave it to the caller to actively decide to use now(); now() could of course be a sane default value for said parameter

2025-01-21 13:20 UTC, zkdev commented on config.py
> +            )[0],
shouldn't we check length?
why is it safe to assume there will be at least one entry?

2025-01-24 12:52 UTC, zkdev approved these changes
/lgtm

2025-01-24 12:59 UTC, merged