Resolve delivery-cfg model dependency towards cc-utils
open-component-model/delivery-service pull request #279
Opened 2024-12-04 12:37 UTC by zkdev

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```action operator
`DeliveryCfg` model from cc-utils will be deprecated and migration to plain `NamedModelElement` will be required.
This change is backwards compatible.
```

2024-12-04 16:09 UTC, 8R0WNI3 requested changes

2024-12-04 16:09 UTC, 8R0WNI3 commented on middleware/auth.py
>              github_cfg = cfg_factory.github(oauth_cfg.github_cfg())
-> `oauth_cfg.github_cfg` (is not callable anymore)

2024-12-04 16:39 UTC, zkdev commented
@8R0WNI3 I agree, we may adjust model and drop some attributes / change some typehints. For now I simply moved all of them and kept model mostly identical.

2024-12-05 14:17 UTC, zkdev commented on config.py
> +    purpose_labels: list[str] = dataclasses.field(default_factory=list)
I am not aware of usages, let's drop it

2024-12-05 15:18 UTC, 8R0WNI3 commented on config.py
> +    algorithm: str = 'RS256'
nit: We _could_ reuse existing enum `Algorithm` from `delivery.jwt` package here. However, I don't have a strong opinion on that considering the downside of the dependency.

2024-12-05 15:18 UTC, 8R0WNI3 commented on middleware/auth.py
> +        for role_binding in oauth_cfg.role_bindings:
not directly related to this PR: Should we also handle the case if no `role_bindings` are configured != `401` for everyone?

2024-12-05 15:18 UTC, 8R0WNI3 commented on config.py
> +    priority: int = 10 # lower values mean higher priority (useful e.g. in rotation scenarios)
I think it would be more intuitive to consider greater values as higher priority, wdyt? Also, what was your rationale to choose `10` as default value? As someone who is responsible for configuration, I think I would expect leaving out the priority to rather evaluate to `0` 🤔

2024-12-05 15:22 UTC, zkdev commented on middleware/auth.py
> +        for role_binding in oauth_cfg.role_bindings:
I recall a discussion we had some days ago, we could instead also define an "everyone" subject(value)

2024-12-05 15:24 UTC, zkdev commented on config.py
> +    priority: int = 10 # lower values mean higher priority (useful e.g. in rotation scenarios)
I translate prio 0 -> "highest priority" 🤔 
With that in mind, 10 is quite a low-priority as default ...

What default do you suggest instead?

2024-12-05 15:43 UTC, 8R0WNI3 commented on config.py
> +    priority: int = 10 # lower values mean higher priority (useful e.g. in rotation scenarios)
As I wrote, I would rather invert logic such that greater values refer to higher priority (-> increasing the value of `priority` acutually increases the priority) and then choose for example 0 as default.

2024-12-05 16:02 UTC, zkdev commented on middleware/auth.py
> +        for role_binding in oauth_cfg.role_bindings:
will address in separate PR

2024-12-05 16:09 UTC, merged