Add authentication via token and enforce authenticated requests
open-component-model/delivery-service pull request #49
Opened 2024-05-27 05:54 UTC by 8R0WNI3

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

2024-05-28 09:36 UTC, zkdev submitted a review, later dismissed
/lgtm

2024-05-28 09:36 UTC, zkdev commented on middleware/auth.py
> +        now = datetime.datetime.now(tz=datetime.timezone.utc)
I was wondering why you are suggesting to change that but I noticed that `utcnow()` is deprecated -> good catch !

2024-06-02 08:40 UTC, ccwienk requested changes

2024-06-02 08:40 UTC, ccwienk commented on app.py
> +        '/.well-known/openid-configuration',
add comment w/ reference to openid-spec (https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfigurationRequest)

2024-06-02 08:40 UTC, ccwienk commented on middleware/auth.py
> +        base_url = f'https://{endpoints.service_host()}'
should we rather pull this up to app.py / a cfg-related module?

2024-06-02 08:40 UTC, ccwienk commented on middleware/auth.py
> +                    'Please add either the url query params "code" and "client_id" '
I think we should rather raise http-401 (authorization required)
nit: I think we should omit courtesies such as "please" from technical error messages ;-)

as for response, we should behave as documented by mdn: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401

2024-06-02 08:40 UTC, ccwienk commented on middleware/auth.py
> +                raise falcon.HTTPBadRequest(f'no such client: {client_id}')
ditto: rather use http-401?

2024-06-02 08:40 UTC, ccwienk commented on middleware/auth.py
> +                t['organization']['login'] + '/' + t['name']
why does login route need to be prefixed w/ gh-org? I saw that this was implemented like that before this change. however, it seems unnecessary / unintuitive to me.

2024-06-02 08:40 UTC, ccwienk commented on middleware/auth.py
> +        # prefer asymmetric signing algorithms before symmetric ones (which don't have a public key)
do we actually want to keep support for symmetric algorithms? we might just as well drop support (and remove code dealing w/ such support)

2024-06-02 08:40 UTC, ccwienk commented on middleware/auth.py
> +class OpenID:
add docstr referencing openid-spec + state this route-class implements auth-flow according to this spec.

2024-06-02 08:40 UTC, ccwienk commented on middleware/auth.py
> +        issuer = get_base_url(
I think it would be better for this route (or actually all routes?) to accept parameters, such as base-url via initialiser. We do use callbacks/lookup to allow for running API-instances to react upon cfg-changes w/o the need to restart the API (which is valid, albeit also not strictly needed, considering we might use k8s-means for downtime-less rolling updates - at the cost of losing in-memory-caches). However, the same can also be achieved if passing callbacks to initialisers.

TLDR; pass-in consumed cfg (including cfg-callbacks/lookups) into initialisers, as opposed to calling them upon requests-processing (dependency-injection / avoid global functions / unexpected scope).

2024-06-02 08:40 UTC, ccwienk commented on middleware/auth.py
> +        self.parsed_arguments = parsed_arguments
I would prefer to not pass-in parsed-args from argparse into routes. Instead, preferably pass used parameters explicitly, or define explicit cfg-types (dataclasses..) in case the amount of passed parameters grows too large.

Rationale: keep dependencies towards consumed objects local and make them more explicit (to make maintenance of our codebase easier).

2024-06-02 08:40 UTC, ccwienk commented on middleware/auth.py
> +        return delivery.jwt.decode_jwt(
considering factoring-out of jwt-handling into `delivery-package`, I think cc-utils is not the ideal place. I think mid-term we should either move client into _this_ repository (including shared utils), or mv common code into a shared (third) repository. It is okay to keep it like this for now, though.

2024-06-03 04:52 UTC, 8R0WNI3 commented on middleware/auth.py
> +                t['organization']['login'] + '/' + t['name']
It's to qualify the team name by its respective GitHub organisation ([ref](https://github.wdf.sap.corp/kubernetes-cicd/delivery-service/commit/5a9f1d6584acc7e868f90d471bd6b0ac340f4059)). So the GitHub organisation name is in the response object under `organization` -> `login` (and `organization` -> `name` as it seems from the api to me).

2024-06-03 04:55 UTC, 8R0WNI3 commented on middleware/auth.py
> +        # prefer asymmetric signing algorithms before symmetric ones (which don't have a public key)
I don't insist on keeping support for symmetric algorithms, however I thought it is not bad to keep it for now (at least for some weeks maybe) to
- keep our current authenticated users logged in (as long as their token is still valid)
- allow other delivery gear instances to smoothly transition to another signing algorithm

2024-06-04 10:54 UTC, zkdev requested changes

2024-06-04 10:54 UTC, zkdev commented on middleware/auth.py
> +                    value=f'no such client: {client_id}',
`www-authenticate` headers are not meant for error messages, but to define what methods are available to gain access for a resource. Thus I would propose to rephrase the value to give a concrete list of available methods / clients.

2024-06-04 10:54 UTC, zkdev commented on middleware/auth.py
> +                t['organization']['login'] + '/' + t['name']
team-names are not unique across multiple github organisations, you can comprehend this e.g. by codeowners syntax -> https://github.com/open-component-model/delivery-service/blob/f2508b6b4444b5d2740a921d6dbc7190aa24b5c0/CODEOWNERS#L2C6-L2C35

2024-06-04 10:54 UTC, zkdev commented on middleware/auth.py
> +                t['organization']['login'] + '/' + t['name']
@ccwienk this has nothing to do with the login route, we only add the team names to the token to enable authorisation based on github team membership

2024-06-04 10:54 UTC, zkdev commented on middleware/auth.py
> +        base_url = 'http://localhost:5000'
deduplicate with `auth.py` (+ other locations?)
either as a constant base-url on app level, or split into hostname, port, ...

2024-06-04 10:54 UTC, zkdev commented on features/__init__.py
> +                parsed_arguments=parsed_arguments,
rather pass the required arguments than the whole parsed object

2024-06-04 11:57 UTC, 8R0WNI3 commented on middleware/auth.py
> +        base_url = 'http://localhost:5000'
Already deduplicated with https://github.com/open-component-model/delivery-service/pull/49/commits/dfd71531d39a424c104d3e7e7df6c31a852a010c

2024-06-04 11:58 UTC, 8R0WNI3 commented on features/__init__.py
> +                parsed_arguments=parsed_arguments,
Ditto, already implemented with https://github.com/open-component-model/delivery-service/pull/49/commits/dfd71531d39a424c104d3e7e7df6c31a852a010c

2024-06-05 06:15 UTC, ccwienk commented on middleware/auth.py
> +                t['organization']['login'] + '/' + t['name']
I see. should we also include the hostname, then (as organisations are also not globally unique)? otherwise, this could actually be used as an exploit (example: if there is privileged and secured team on GHE-instance A, an attacker with control over the equally-named GHE-instance B (which would need to be included in trusted GHE-instances, of course) could create equally-named org + team(s) and thus circumvent auth-mgmt.

2024-06-05 06:16 UTC, ccwienk requested changes
see my latest comment

2024-06-05 07:50 UTC, merged