Allow rescorings for findings of type `malware`
open-component-model/delivery-service pull request #62
Opened 2024-06-06 06:51 UTC by zkdev

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

2024-06-07 04:55 UTC, 8R0WNI3 requested changes

2024-06-07 04:55 UTC, 8R0WNI3 commented on compliance_summary/__init__.py
> +            ),
We should also remove existing compliance summary entry for type `malware` here.

2024-06-07 04:55 UTC, 8R0WNI3 commented on components.py
> +            dso.model.Datatype.MALWARE_FINDING,
I think we must also query for `ARTEFACT_SCAN_INFO` here + then check in subsequent functions whether the component was scanned or not.

2024-06-07 04:55 UTC, 8R0WNI3 commented on rescore.py
> +            if isinstance(data.finding, dso.model.S3MalwareFinding):
This should be `OCIMalwareFinding`, shouldn't it?

2024-06-07 04:55 UTC, 8R0WNI3 commented on rescore.py
> +                if isinstance(data, dso.model.OCIMalwareFinding):
Ditto (-> `S3MalwareFinding`) + rather put type specific attributes into condition instead of early exiting (this will ease adding new malware finding types)

2024-06-17 09:16 UTC, ccwienk requested changes

2024-06-17 09:16 UTC, ccwienk commented on rescore.py
> +            if isinstance(data.finding, dso.model.S3MalwareFinding):
generally speaking, I think it is a bad idea to have accesstype-specific classes for malware-findings. instead, there should preferably be _one_ class for malware-findings, which roughly resembles the following structure:

- attributes identifying the malware (I think this is a single str w/ malware-name)
- metadata about malware scan (db-version, scan-times, etc)
- correlation-id for the finding
- ocm-coordinates

2024-06-18 14:58 UTC, zkdev commented on components.py
> +            dso.model.Datatype.MALWARE_FINDING,
was implemented with https://github.com/open-component-model/delivery-service/commit/48c121ea

2024-06-18 15:00 UTC, zkdev commented on compliance_summary/__init__.py
> +            ),
I will rm old malware findings related code in a separate PR, once findings have been migrated on db level (we need to keep track of scans, even if they did not yielded results)

2024-06-18 15:24 UTC, zkdev commented on rescore.py
> +            if isinstance(data.finding, dso.model.S3MalwareFinding):
address with https://github.com/gardener/cc-utils/pull/985

will update this PR accordingly (once we came to an agree in cc-utils PR)

2024-06-20 04:37 UTC, 8R0WNI3 reviewed
mostly lgtm

2024-06-20 04:37 UTC, 8R0WNI3 commented on rescore.py
> +            finding_matching_am = tuple(
Is there actually a case where there are multiple "matching" malware findings for one and the same ocm artefact? If you refer to BDBA findings for example, this is the case if just the package version is different, since we group the findings across multiple package versions there. However, I don't see any case where we would have multiple malware findings here 🤔 If not, I suggest to remove the parts with the `finding_matching_am` here.

2024-06-20 08:47 UTC, ccwienk commented on rescore.py
> +            finding_matching_am = tuple(
preferably, do not abreviate art(e|i)fact_metadata with just `am`. (entire module). if scope is very limited (e.g. for-loop with a couple of lines of code), it is okay to use very short variables (i, a, m, ....) in some cases. in other cases, preferably do not use such uncommon abbreviations

2024-06-20 08:47 UTC, ccwienk commented on rescore.py
> +        elif am.meta.type == dso.model.Datatype.MALWARE_FINDING:
if Datatype is an enum, use identity-comparison (is instead of ==) + meta.type should be "casted" to enum (if it is an enum)
naming-nit: typically, classnames should user PascalCase (pep8); also, considering we call our entries artefact-metadata, rather call the type similarly (e.g. MetadataType, or ArtefactMetadataType)

2024-06-20 08:48 UTC, ccwienk commented on rescore.py
> +                        'virus_name': am.data.finding.virus_name,
if it is not yet too late, I would prefer usage of `malware` rather than `virus`, as this is the more generic term (there is malware, such as worms, backdoors, etc. that is not considered a `virus`)

2024-06-20 11:15 UTC, zkdev commented on rescore.py
> +        elif am.meta.type == dso.model.Datatype.MALWARE_FINDING:
`Datatype` is a class whereas `MALWARE_FINDING` is a constant class-field (-> uppercase)

2024-06-20 11:16 UTC, zkdev commented on rescore.py
> +        elif am.meta.type == dso.model.Datatype.MALWARE_FINDING:
see https://github.com/gardener/cc-utils/blob/bb075a96fff8c59fc9493480222b1fa9006d6f16/dso/model.py#L120

2024-06-20 11:16 UTC, zkdev commented on rescore.py
> +        elif am.meta.type == dso.model.Datatype.MALWARE_FINDING:
will address rename of `Datatype` in separate PR

2024-06-20 11:52 UTC, 8R0WNI3 approved these changes

2024-06-20 12:22 UTC, zkdev commented
linter can be ignored as this is just missing an upstream (cc-utils) change

2024-06-20 12:22 UTC, merged