Initialise local setup using kind
open-component-model/delivery-service pull request #84
Opened 2024-06-24 15:55 UTC by 8R0WNI3

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
Documentation about "how to run it locally using kind" will also be added to this PR later.

**Release note**:

```improvement operator

```

2024-06-25 21:07 UTC, zkdev reviewed
diff looks good, will test setup myself tomorrow

2024-06-25 21:07 UTC, zkdev commented on features/__init__.py
> +            return k8s.util.kubernetes_api(kube_config_path=self.kube_config_path)
nit: `kubeconfig` is an established term, let's use it consistently (over `kube_config`)

2024-06-25 21:07 UTC, zkdev commented on local-setup/kind/kind-up.sh
> +rm ${CHART}/values-delivery-service.yaml # is created every time from base file in `seriallise_cfg.py`
nit: typo in `seriallise_cfg.py`

2024-06-26 04:32 UTC, 8R0WNI3 commented on features/__init__.py
> +            return k8s.util.kubernetes_api(kube_config_path=self.kube_config_path)
Agreed, I was thinking the same at first but then I saw that the kubernetes module is internally referring to `kube_config` so I decided to go with the argument name `--kubeconfig` and the variable name `kube_config`. However, thinking about it again we may should rather be consistent in our codebasis than complying to other codebases. Will adjust :-)

2024-06-26 15:24 UTC, ccwienk requested changes

2024-06-26 15:24 UTC, ccwienk commented on features/__init__.py
> +    def get_repo(self) -> github3.repos.Repository | str:
nit: why do we need getters? 🤔 

letting that aside: I think it is not that nice to keep in the same attribute a reference to either a path to a directory containing certain files vs. a gh3-repository-object. could we instead rather abstract from that in that this class might directly yield the data of interest (so the underlying data-source would be an implementation-detail hidden by this class?

2024-06-26 15:24 UTC, ccwienk commented on k8s/util.py
> +        kubeconfig = yaml.load(open(kubeconfig_path), Loader=yaml.SafeLoader)
nit: it is slightly shorted to use `yaml.safe_load` shorthand.

2024-06-26 15:24 UTC, ccwienk commented on local-setup/cfg/serialise_cfg.py
> +        file.write(yaml.dump(values))
preferably use yaml.safe_dump

2024-06-26 15:24 UTC, ccwienk commented on local-setup/cfg/serialise_cfg.py
> +    cluster_dir = ci.util.check_env('PATH_CLUSTER_CHART')
nit: maybe we should avoid adding new dependencies to ci.util (keep them centralised at ctx_util) ; in particular, the effect of doing an unchecked os.environ['FOO'] is almost the same (only difference: there will be a KeyError, so it will be a little less obvious we expected a certain env-var to be present - which should however be quite obvious from stacktrace... )

2024-06-26 15:24 UTC, ccwienk commented on local-setup/cfg/serialise_cfg.py
> +    values = yaml.load(open(values_base_file), Loader=yaml.SafeLoader)
nit: yaml.safe_load

2024-06-26 15:24 UTC, ccwienk commented on local-setup/cfg/sprints.yaml
> +    end_date: '2024-12-11T00:00:00+01:00'
nit: maybe we should rather add a template here and generate the raw data. rationale: otherwise, the contents will outdate quite soon, and will have to be manually maintained

2024-06-26 15:24 UTC, ccwienk commented on local-setup/kind/cluster/values-delivery-db.yaml
> +fullnameOverride: delivery-db
generally speaking: do we actually need postgres for local setup? in earlier times, sqlite worked reasonably well, and would slightly reduce footprint

2024-06-26 15:24 UTC, ccwienk commented on local-setup/kind/cluster/values-delivery-gear-extensions.yaml
> +        # artefactEnumerator:
what's the purposes of this commented-out spec? should users un-comment parts or all of it?

2024-06-26 15:24 UTC, ccwienk commented on local-setup/kind/kind-up.sh
> +    --version 10.12.4 \
hmmm...... is this a good place to place postgres-version?

2024-06-26 15:24 UTC, ccwienk commented on local-setup/local-setup.md
> +### Clamav
nit: ClamAV

2024-06-26 15:24 UTC, ccwienk commented on local-setup/local-setup.md
> +To set up the GitHub issues extension, you need to add the configuration via `configuration.scanConfigurations.[].spec.issueReplicator`. Also, you have to make sure you have GitHub credentials provid
again, some quite lenghty lines :-/
I guess, markdown will not allow is to break them, w/o translating that into HTML, though, right (which is also undesirable for users reading the HTML variant)? :(

2024-06-26 15:24 UTC, ccwienk commented on yp.py
> +    repo: github3.repos.Repository | str,
I think it is not nice to name this parameter `repo` :-/
same for other occurrences in this file

2024-06-26 15:32 UTC, 8R0WNI3 commented on app.py
> +        help=(
Why should this be preferable? I'm asking because at most places in our code base of the delivery-service we use this style and changing it here would be quite inconsistent then.

2024-06-26 15:37 UTC, 8R0WNI3 commented on local-setup/kind/cluster/values-delivery-gear-extensions.yaml
> +        # artefactEnumerator:
If it is commented out, the respective extensions won't be included in the local setup. This is the default. If the user wishes to include one or multiple extensions, this commented-out spec serves as a base configuration so that the user has minimal efforts to configure them (see `local-setup.md` for required steps).

2024-06-26 16:01 UTC, 8R0WNI3 commented on config.py
> +        logger.warning(f'failed to retrieve issue repository; {e}')
This is not about disabling a functionality, but rather shifting the point of failure some lines in the code later (i.e. until [here](https://github.com/open-component-model/delivery-service/blob/b70feabba9dbeba9d5f5e9f8c4f0e6c8974ab890/issue_replicator/__main__.py#L593)). By that, other extensions (which don't require this GitHub access) are able to run properly while the issue replicator (which requires it) still fails at usual (just some lines later with the hint that it failed to retrieve the GitHub repository). And from here Kubernetes self-healing kicks in just like before.

However, I agree to make the log output more self-explanatory 👍🏼

2024-06-26 16:30 UTC, 8R0WNI3 commented on local-setup/kind/cluster/values-delivery-db.yaml
> +fullnameOverride: delivery-db
Out-of-the-box sqlite will not work with the deployed delivery-service since we don't include it in our images (yet). Also, extensions like the `deliveryDbBackup` rely on the database being a postgres instead of sqlite. Next to that, with a postgres it is closer to a productive scenario so development and testing might have better results compared to testing with sqlite. And last but not least, also supporting sqlite here means double efforts regarding implementation and maintenance. Wdyt?

Nevertheless, you can still run a local delivery-service (not in Kind) using sqlite and connect to the Kind cluster. It's currently just not supported for the deployment.

2024-06-26 16:42 UTC, 8R0WNI3 commented on features/__init__.py
> +    def get_repo(self) -> github3.repos.Repository | str:
We have getters so that we can just pass callbacks to subsequent functions instead of the value directly. We decided on this already a long time ago because we wanted to support changes in the features config without requiring the delivery-service to restart (using `watchdog.observers`). I'm very open to discuss to drop this support and instead utilise Kubernetes for restarting purposes, but I would not include this in this PR.

Regarding your second point: The reason to not yield the data of interest directly was that the repository object itself was of interest as well I suppose (e.g. to also provide information on where the data comes from). However, I'd suggest to maybe split this into two functions, one yielding the data and one the datasource. Wdyt?

2024-06-27 13:12 UTC, ccwienk approved these changes

2024-06-27 13:12 UTC, ccwienk commented on app.py
> +        help=(
in my opinion, multiline-str-literals are more convenient, as e.g. you do not have to deal with details, such as keeping trailing whitespace for word boundaries + there is slightly less noise from str-termination-characters ('|"). So I would argue multiline-str-literals are easier to read and more comfortably to edit (think about changes in line-wrapping), which is why I would (almost?) always prefer them over concatenating single strs.

consistency might be a reason (although I do not think mixing those two styles is intolerable). maybe we should align for our entire codebase on such coding style preferences, though 🤔

2024-06-27 13:12 UTC, ccwienk commented on local-setup/cfg/sprints_base.yaml
> +# sprints are generate automatically using `render_sprints.py` script during "kind-up"
nit (typo): generate_d_

2024-06-27 14:45 UTC, 8R0WNI3 commented on app.py
> +        help=(
I adjust it according to your suggestion.

2024-06-27 14:50 UTC, zkdev commented on local-setup/local-setup.md
> +## Configuration
add note on how to update config (only on cluster re-creation?)

2024-06-27 15:14 UTC, zkdev commented on local-setup/cfg/sprints_base.yaml
> +sprints: []
`localhost:5000/delivery/sprint-infos/current` return HTTP 500

2024-06-28 06:06 UTC, 8R0WNI3 commented on local-setup/local-setup.md
> +## Configuration
I added the `kind-update` script to upgrade existing helm charts using the updated local configuration without the need to re-create the cluster. Also, I added a small paragraph to the documentation.

2024-06-28 06:08 UTC, 8R0WNI3 commented on local-setup/cfg/sprints_base.yaml
> +sprints: []
The sprints and the addressbook are now both mounted via volume to the delivery-service pods. By that, they don't require access to a remote repository anymore to enable these features. However, since the change that these features can be configured via local configuration is part of this PR and not yet included in the images, the local startup will still fail until this change is rolled-out.

2024-06-28 10:22 UTC, zkdev approved these changes
/lgtm

2024-06-28 10:22 UTC, merged