Add runtime artefacts as CRD to extension workflows
open-component-model/delivery-service pull request #90
Opened 2024-06-28 11:59 UTC by 8R0WNI3

**What this PR does / why we need it**:
This change introduces the handling for a new Kubernetes custom resource definition (CRD) `RuntimeArtefact`. Its purpose is to represent those artefacts, which are not part of OCM but still need to be processed in several extensions of the OCM-Gear, such as the artefact enumerator or the issue replicator. Just as component descriptors are created and uploaded independently of the OCM-Gear, those runtime artefacts should also be created/updated/deleted by external tooling which has knowledge of existing runtime artefacts. Therefore, this change also adds new API routes supporting this request. As soon and as long a CR for a runtime artefact exists, it will be part of the extension machinery just as traditional OCM resources and sources, except they won't be enriched by extra information which was usually retrieved from the component descriptor.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

2024-07-02 19:02 UTC, ccwienk requested changes

2024-07-02 19:02 UTC, ccwienk commented on service_extensions.py
> +            - label (optional): `<key>:<value>` formatted label to use as filter \n
is it still necessary to add those bogus `\n`s? I really very strongly dislike polluting our codebase as a workaround for a broken/buggy lib generating some documentation, and would actually prefer to keep our code clean and either fix doc-generator / use different generator, or choose another approach for generating documentation

2024-07-03 06:45 UTC, 8R0WNI3 commented on k8s/runtime_artefacts.py
> +    `True` if a new runtime artefact was created, otherwise `False`.
Yes, the purpose of this was that if there are 2 different sources of runtime artefacts (i.e. 2 different scanner), which both process the same runtime artefact, they should not be mixed-up. That's because they'll have to take care of maintaining the lifecycle of the runtime artefact and if one scanner deletes it, it must not be deleted for the other scanner. So, I'd suggest to create the "same" runtime artefact for both scanner by providing different labels. On our end, i.e. in the artefact enumerator or issue replication, this wont' have an effect since we deduplicate the artefacts.

2024-07-03 08:11 UTC, 8R0WNI3 commented on issue_replicator/github.py
> +    ocm_nodes: collections.abc.Iterable[cnudie.iter.ResourceNode | cnudie.iter.SourceNode],
Actually, I was able to drop the `artefacts` parameter entirely and just make use of `ocm_nodes`.

2024-07-03 08:56 UTC, 8R0WNI3 commented on issue_replicator/github.py
> +        component_descriptor_lookup=component_descriptor_lookup,
Generally speaking, I totally agree to do a lookup in the first place and then work on the results. Actually, I did so in my first iteration. However, in this specific case I've found it quite convoluted because:
1. OCM component descriptors can only be retrieved in case of resources/sources, so one definitely needs artefacts of type `ComponentArtefactId` for runtime artefacts
2. for resources and sources, one could either drop the `artefacts` param and just use the lookup results `ocm_nodes`, or one could use `artefacts` in general and the lookup results only to provide extra information, e.g. about the access
3. either way, subsequent coding must be able to differentiate between both cases and add some extra handling, e.g. retrieval of component name from an OCM node instead of CAI because the data structure differs
4. based on how (2) is implemented, one has to take care of merging `artefacts` and `ocm_nodes` again

Instead, I'd suggest to push the actual lookup back as far as possible here, so that most coding is the same, independently of whether it is a resource, source or runtime artefact, and only lookup extra information from the component descriptor where it is actually required. Wdyt?

2024-07-03 09:34 UTC, 8R0WNI3 commented on service_extensions.py
> +            - label (optional): `<key>:<value>` formatted label to use as filter \n
Yes it is still required -> [see](https://github.com/0b01001001/spectree/blob/8967d2ff697a07f9868bcf95a9470490f111d746/spectree/utils.py#L74): double line-breaks are kept but single line-breaks are just replaced by spaces. So I think from the perspective of the lib this is rather a feature than a bug 🙈

2024-07-08 11:10 UTC, ccwienk commented on service_extensions.py
> +            - label (optional): `<key>:<value>` formatted label to use as filter \n
In this case, I think we should rather switch to a different approach for generating api-documentation, instead of adding such noise to our codebase :-/

2024-07-08 11:12 UTC, ccwienk commented
@8R0WNI3 : generally speaking (just judging from pullrequest summary), do you think it would make sense to also replicate component-descriptors "of interest" to CRDs (for the sake of consistency)?

2024-07-08 11:18 UTC, ccwienk approved these changes

2024-07-08 11:18 UTC, ccwienk commented on k8s/util.py
> +        if e.status != http.HTTPStatus.NOT_FOUND:
nit: if this is a repetitive pattern, we might consider implementing a util function / decorator ("absent_ok" or similar)

2024-07-08 11:18 UTC, ccwienk commented on k8s/runtime_artefacts.py
> +import dataclasses
it might be nice to add a docstr for entire module to explain what it is about (keep track of runtime-artefacts ...)

2024-07-08 11:26 UTC, ccwienk commented on k8s/runtime_artefacts.py
> +class RuntimeArtefact:
docstr would be nice, explaining what a runtimeartefact is semantically. Specifically, it would be worth mentioning that runtime artefacts are related to OCM Components (/artefacts), but are, well, runtime instances derived from OCM artefacts.

btw: (how) can we currently keep track of this link between OCM <-> runtime? by using OCM-Component to identify the OCM-Component (e.g. gardener landscape), and using the runtime resource to describe the runtime-artefacts (e.g. seed cluster(s))?

Maybe, we should make this slightly more explicit, and have a pair:
- OCM Component (s) - might be more than one, but for the sake of simplicity, we could stick to 1 for design-time
- runtime artefact(s) - ditto: we could stick to 1

My rationale behind that is a scenario like the following:

*cluster(s) within running landscape*
 -> design-time: reference to landscape (either landscape-component, or lss-version); might be more specific, e.g. by referencing nested component (e.g. just gardener-dashboard)
 -> runtime: reference to running landscape + path to nested runtime-artefact within landscape

If we start w/ having pairs of references (design-time vs run-time), we might be better-prepared for similar future cases

2024-07-10 04:26 UTC, merged